### ISSUE TITLE
Compatibility with terrain layer

### ISSUE THREAD

**Issue by DarKDinDoN** [manuelVo/foundryvtt-drag-ruler#1]
Hello,

Thx for continuing this great module!

Can you make this module compatible with Terrain Layer? https://github.com/wsaunders1014/TerrainLayer

**Comment by UnoriginalDM** [comment]
hey manuelVo thanks for the new mod. Just a heads up (if you are not aware already), but terrain layer relies on the Difficult Terrain mod I believe. Inside of that mod there is a setting that may help getting your mod to work with theirs.
![image](https://user-images.githubusercontent.com/77896718/106596781-1bceeb80-651b-11eb-9bca-e1a48649b3ea.png)

**Comment by DarKDinDoN** [comment]
@UnoriginalDM I think this is the other way around. Difficult Terrain relies on Terrain Layer.

**Comment by UnoriginalDM** [comment]
@DarKDinDoN Yes, I stand corrected. My bad.

**Comment by JamzTheMan** [comment]
Here to 👍 this request. I'd love to switch over to a "maintained" module but Difficult Terrain adjustments (and right-click way points) are critical use and reason we use Show Drag Distance + Terrain Layer.
