### ISSUE TITLE
Handle "ctrl+z" shortcut

### ISSUE THREAD

**Issue by happy-cujo** [manuelVo/foundryvtt-drag-ruler#100]
I'm not sure if it's doable, but:

When you move token you're able to perform undo action by pressing "ctrl+z". It would be nice if such action instead of adding new way point in movement history removed related one.

It kinda makes sense to allow reverting player movement after "Oh, so this yellow square is a flame? Ok, I would like to not go there then" situation.

**Comment by manuelVo** [comment]
Duplicate #64
