### ISSUE TITLE
moveToken uses old "setSnapParameterOnOptions" call

### ISSUE THREAD

**Issue by MAClavell** [manuelVo/foundryvtt-drag-ruler#102]
Was updating Toggle Snap to Grid to work with the newest update's features and noticed that "setSnapParameterOnOptions" in ruler.js moveToken was using the old call. Was causing all waypoints to be centered when another is added. Felt like this didn't warrant a full pull request ;)
It should be: `setSnapParameterOnOptions(this, options);`
Instead of `setSnapParameterOnOptions(this, event, options);`

**Comment by manuelVo** [comment]
This would totally warrant a PR - anything that does a productive change would, even if it's very smal :)
