### ISSUE TITLE
Conflict with FoundryVTT Arms Reach

### ISSUE THREAD

**Issue by LordOHelmet** [manuelVo/foundryvtt-drag-ruler#106]
### Environment Details
* Foundry VTT Version: 0.8.9
* Operating System: Windows
* How Are You Using Foundry: Froge with Chrome
* Which Game System: GURPS

### Issue Description

When both modules, Arms Reach and Drag Ruler are enabled Drag ruler doesn't show the distance any more.

**Comment by manuelVo** [comment]
Duplicate of #105
