### ISSUE TITLE
Right Click and Spacebar cancels movement

### ISSUE THREAD

**Issue by DuckDungeon** [manuelVo/foundryvtt-drag-ruler#109]
Have tried with only drag ruler module active and what should be a waypoint cancels the drag. 
No idea what's going on.

**Comment by manuelVo** [comment]
Am I understanding this correctly, that both right click and spacebar cancel the movement? What do your settings look like?

**Comment by DuckDungeon** [comment]
Partly, it is whatever button is set for waypoints. I prefer right click, but when it started happening I switched to spacebar to see if that would solve the issue. It did not, just canceled the movement. 

I run with many modules, including terrain ruler and enhanced difficult terrain. But even when all those were off, I still have that issue. Even with the only module being drag ruler this problem persists. 

On chrome on mac if that makes a difference. The Server runs off a mac too.

Took screenshots of the Drag Ruler settings, hoping that they are helpful. It is very odd that it keeps happening.
<img width="598" alt="Screen Shot 2021-08-30 at 4 43 08 PM" src="https://user-images.githubusercontent.com/66494204/131410305-9d5c4a1b-3bfa-410f-a07b-9e538e18c624.png">
<img width="601" alt="Screen Shot 2021-08-30 at 4 43 16 PM" src="https://user-images.githubusercontent.com/66494204/131410311-eef9bedf-ec15-4f90-a298-9dfdf4da5ff7.png">


The module is fantastic besides, won't stop using it, just found it weird.

**Comment by manuelVo** [comment]
With these settings, what happens when you press space bar? And what happens if you right-click?

**Comment by DuckDungeon** [comment]
With the settings in screenshot, right-click cancels movement and spacebar does nothing. 

If "swap spacebar and right-click" is selected, the opposite is true: right-click does nothing and spacebar cancels movement.

**Comment by manuelVo** [comment]
After you press spacebar and nothing happens, is there an error in the js console? (The js console opens up with F12)

**Comment by DuckDungeon** [comment]
Please excuse my ignorance, coming from roll20 and expecting how that functions. It is working—I had been using it with the belief that the opposite was true of the "swap spacebar and right-click" option and didn't realize that the right-click was actually supposed to cancel movement.

Thank you for your help. Again, great module, loving Foundry, but still the new guy.

**Comment by DuckDungeon** [comment]
Figured this out after seeing no errors, so thanks for that trick as well
