### ISSUE TITLE
Support for multiplier of speed with unique color - PF2, 5E Dash support

### ISSUE THREAD

**Issue by apoapostolov** [manuelVo/foundryvtt-drag-ruler#11]
This request is for support for multiple multipliers of the speed (x1 to x2, x2+ to x3, x3+ onward) with unique color for each assigned in setting by DM for the whole game. This will allow for:

- in 5E, x1+ to x2 will be considered if the user took Dash, x2+ to x3 will be considered if the user took Dash + Cunning Action
- in PF2, x1+ to x2 will be considered 2nd Stride, x2+ to x3 will be considered 3rd Stride
- In both cases x3+ will be colored as unavailable distance (i.e. transparent black).

**Comment by manuelVo** [comment]
There is support for an unlimited amount of colors available via the module's API, that can be used by game systems or other modules. There are two reasons for why only one speed multiplier is available without the api.

The first reason is that for all the game systems I know there either is no third speed range or it's awfully conditional. Like in DnD it's only available to rogues with level 2+ and in pathfinder 1 the second multiplier can be x3 or x4 depending on whether the character is wearing heavy armor. For this reason I think a second flat multiplier wouldn't be all that useful for most players.

The second reason is that a settings screen that allowed for unlimited multipliers would be pretty time-consuming to write (and probably not easy to use). For this reason I think it's preferable to set a limit on the amount of multipliers that's available, and that limit should be at the point where it's most useful most of the players. For the reasons I detailed above currently consider that limit to be at one multiplier.

I'm willing to increase the amount of multipliers provided by default if there are more game systems out there that use a second flat multiplier, but as long as it's only one or two systems that would profit from that I prefer sticking to offering only one multiplier.

**Comment by manuelVo** [comment]
A module to integrate drag ruler into Pf2 exists now (https://foundryvtt.com/packages/pf2e-dragruler/). A third color for dnd5e seems pretty nieche to me, so I'm closing this for now untilbI become aware of more game systems that need this feature.
