### ISSUE TITLE
[Feature Suggestion] Reset/Undo Button/Shortcut

### ISSUE THREAD

**Issue by GhostwheelX** [manuelVo/foundryvtt-drag-ruler#117]
Might it be possible to have a button or shortcut that would reset the selected creature's movement (both placement on canvas and history) to where they started on the current turn? (Or undo the last movement they made?) Would help a ton with verifying movement if someone changes their mind.

Thanks!

**Comment by manuelVo** [comment]
There's Ctrl+Z to undo one movement (can ne used multiple times). Would that work for you?

**Comment by GhostwheelX** [comment]
Ah, had not realized that. Works well, thank you!
