### ISSUE TITLE
Add option to show drag ruler only for friendly tokens

### ISSUE THREAD

**Issue by ckdragons** [manuelVo/foundryvtt-drag-ruler#118]
As a GM, I may not want my neutral and hostile tokens showing their paths until I release them to move. Or at least not show the path when I don't use the stat blocks in Foundry (using the PF1E Lite sheet). So the movement is incorrect many times since it defaults to 30 feet.

**Comment by manuelVo** [comment]
I'm not quite sure what the exact thing you're requesting is. The first part of your request sounds like you'd prefer to not have the path shown at all, while the part about the movement speed indicates that it's the incorrect coloring of the path that you take issue with. Which of the two is it?

**Comment by ckdragons** [comment]
My apologies for the confusion. Please disregard. I've decided on a work around instead. Appreciate your quick response.
