### ISSUE TITLE
Add compatibility with with Hex Token Size Support module

### ISSUE THREAD

**Issue by dirusulixes** [manuelVo/foundryvtt-drag-ruler#12]
At the moment Drag Ruler does not work if [Hex Token Size Support module](https://github.com/Ourobor/Hex-Size-Support) is used. The ruler does not appear and the token does not complete the movement.

**Comment by manuelVo** [comment]
[Related PR in the Hex Token Size repository](https://github.com/Ourobor/Hex-Size-Support/pull/9)
