### ISSUE TITLE
Drag Ruler always shows red color instead of the green->yellow->red

### ISSUE THREAD

**Issue by Aggrus** [manuelVo/foundryvtt-drag-ruler#125]
I noticed that instead of showing the normal green color for the standard movement distance, drag ruler is showing red. Video for example:

https://user-images.githubusercontent.com/40422088/139631894-8c69973d-ba6e-4be7-9b0a-8aa7c72e0659.mp4

**Comment by manuelVo** [comment]
Which game system are you using?
Which Speed Provider are you using and how is it configured?
Please check the js console (opens with F12). Are there any errors (red) or warnings (yellow)? If so please post them here.

**Comment by Aggrus** [comment]
First two questions are answered in the video, but system is dnd5e 1.5.3 and speed is configured to data.attributes.movement.walk.

I have confirmed its a module conflict, just don't know which modules are causing it yet...

**Comment by Aggrus** [comment]
Okay, I just checked on another game, seems the name for the speed provider was wrong is all,  thanks for the quick response, I'll close the issue as it was just my lack of attention hahahah
