### ISSUE TITLE
Token doesn't follow waypoints unless they are double set when enhanced terrain layer is active.

### ISSUE THREAD

**Issue by asdexter** [manuelVo/foundryvtt-drag-ruler#126]
If I set a series of way points, the token moves from the start point directly to the end point when it moves.

The token will follow the waypoints if I set the same waypoint twice in a grid square.

This bug only occurs when the enhanced terrain layer module is active.

**Comment by manuelVo** [comment]
Open the console by pressing F12 and check if there are any errors (red) or warnings (yellow) there. If so, please post them here.

**Comment by manuelVo** [comment]
Apparently this bug has been resolved recently. Please ensure you're on the latest version of Enhanced Terrain Layer

**Comment by asdexter** [comment]
I just installed it today, confirmed all are up to date. The console shows a warning when i select a token and start to drag. Warning text is as follows:

Enhanced Terrain Layer |  terrainAt is deprecated and will be removed, please use terrainFromGrid or terrainFromPixels instead
warn @ terrain-main.js:14

**Comment by manuelVo** [comment]
Do you have modules other than socketlib, Enahnced Terrain Layer, Terrain Ruler and Drag Ruler enabled? If so, does this bug still happen if you disable all other modules?

**Comment by Marcloure** [comment]
I can confirm I have the same bug, it happens even with only Enhanced Terrain Layer, Drag Ruler, and socketLib modules activated

**Comment by asdexter** [comment]
I just checked and the issue happens as soon as enhanced terrain layer is activated. I'm guessing the deprecation warning is involved.

**Comment by manuelVo** [comment]
This bug appears to be caused by a recent update of Enhanced Terrain Layer. I've informed the author of that module about the details.

**Comment by manuelVo** [comment]
This should now be foxed with the Ehnanced Terrain Layer 1.0.34 update. Can you confirm this?

**Comment by Marcloure** [comment]
Yup, seems fixed here
