### ISSUE TITLE
Dash multiplier doesn't seem to make any changes

### ISSUE THREAD

**Issue by SLinxTheFox** [manuelVo/foundryvtt-drag-ruler#127]
Just title. i can have it at 2 or 10 and it's not any faster. i made sure it was up to date about 2 hours ago or so

**Comment by manuelVo** [comment]
Please set the dash multiplier to 10 and post a screenshot where you drag your token until the red color appears.

**Comment by SLinxTheFox** [comment]
Crap, i misunderstood. I thought it meant that, when dashing, the token would move faster, as that was a feature I wanted.
