### ISSUE TITLE
Symbaroum drag ruler integration

### ISSUE THREAD

**Issue by Surcof** [manuelVo/foundryvtt-drag-ruler#128]
Hi there i'm using Symbaroum and there the movement is fixed (10 m or 30 ft) how can i give the module the fixed speed?

**Comment by manuelVo** [comment]
Hi. Fixed speeds aren't supported by Drag Ruler's Generic Speed Provider. What you could do however to make this possible, is writing a custom Speed Provider for the Symbaroum game system via [Drag Ruler's API](https://github.com/manuelVo/foundryvtt-drag-ruler#api). Doing so only requires a few lines of code and could be done either by the Symbaroum game system directly or by a separate module.

**Comment by Surcof** [comment]
i have followed your advice and i have created a superr stupid script, can you add it in the section "Game systems with Drag Ruler integration" via module?
link at it 
https://github.com/Surcof/symbaroum-drag-ruler-integration-main

**Comment by manuelVo** [comment]
Sorry for the long delay. I got a pretty busy schedule lately and didn't get around to doing anything for foundry. Your module is now part of the list.
