### ISSUE TITLE
Add Translate french

### ISSUE THREAD

**Issue by Elfenduil** [manuelVo/foundryvtt-drag-ruler#129]
Hi,

Can you add the translate french in your module, see file in Att.

Thank you
[Traduire Drag Ruler.txt](https://github.com/manuelVo/foundryvtt-drag-ruler/files/7595393/Traduire.Drag.Ruler.txt)

**Comment by manuelVo** [comment]
Hi there. Requests to add/change files are usually done through the Pull Request feature of Github, which makes the process of review much easier.

At the bottom of the file you've attached there are serveral strings still in english (under "swapSpacebarRightClick" and "useGridlessRaster"). Did you miss those?

**Comment by manuelVo** [comment]
Thanks!

**Comment by manuelVo** [comment]
I've merged this for now as is. Thanks for the translation! If you're interested in translating the strings that were added with the v9 port freel free to add a new PR :)
