### ISSUE TITLE
Measurement Template Support

### ISSUE THREAD

**Issue by n0q** [manuelVo/foundryvtt-drag-ruler#13]
The option to precisely move measurement templates the way you move tokens would be very useful for certain systems.

**Comment by manuelVo** [comment]
Do I understand your request correctly in that you want the Drag Ruler to appear when you're dragging a measurement template around the screen?

**Comment by n0q** [comment]
That's right. I could see making this a toggle in the module options. It would be quite useful, though.

**Comment by JamzTheMan** [comment]
Actually this could be useful for things like "Cloud" spells that drift 10-20 feet/round or other persistent AoE spells that a magic user may be able to move around.

FWIW it would need to hand intersection to intersection or cell to cell movement cases.
