### ISSUE TITLE
[Feature Request] Account for multiple speed attributes

### ISSUE THREAD

**Issue by MarkeyMarke** [manuelVo/foundryvtt-drag-ruler#130]
There's multiple movement attributes in D&D5e (fly, hover, climb, swim, etc):
![image](https://user-images.githubusercontent.com/32396474/143304916-a8aded45-1e4d-412f-95dd-e2fd93b5c95c.png)

It would be great to have a setting to set multiple speed attributes and take the highest one.

**Comment by manuelVo** [comment]
Hello. This can be achieved via [Drag Ruler's API](https://github.com/manuelVo/foundryvtt-drag-ruler#api), either by the game system directly or by a separate module. Examples of game systems doing this are [Pathfinder 1](https://gitlab.com/Furyspark/foundryvtt-pathfinder1/-/blob/8bc9633d1fddce0b45b64695a203da00c91ed71c/module/modules.js#L12-90) (directly in the game system) and [Pathfinder 2](https://github.com/League-of-Foundry-Developers/pf2edragruler) (as a separate module).

**Comment by MarkeyMarke** [comment]
Ah, I see, it will take some work learning to do this but that should suffice

**Comment by manuelVo** [comment]
If you need any help, let me know
