### ISSUE TITLE
Support of euclidean diagonal movement

### ISSUE THREAD

**Issue by veithflo** [manuelVo/foundryvtt-drag-ruler#134]
Hi there. thank you for spending your time to make this great addon.
In my friend group, we were used to use an euclidean. Is there a chance you will support that movement type?

**Comment by manuelVo** [comment]
Hello, thanks for the kind words. Do you have the Terrain Ruler module enabled in your world?

**Comment by veithflo** [comment]
Hello. Yes at this moment i'm also using Terrain Ruler, but with or without it, the Drag Ruler don't seem to support Euclidean movement type. Even worse, the Terrain Ruler messes with the default distance meassurement tool, forcing it to use also the 5/10/5 rule. That's very confusing for me and my players, because you "measure" 6m but then when placing your 6m measure template (cone, sphere, line) it's not within template range.

I've also tried to add the "EUCL" movement type myself into Terrain Ruler, but the grid-by-grid-splitting is to hard to handle and bypass for me. For movement distance calculation the Euclidean way should be easier than any others as you just have to calculation the distance using Pytagoras between each waypoint. Only when using Terrain Ruler with difficult terrain, it's necessary to know what grid fields has been entered during movement, checked with the grid-by-grid-splitting, to add the movement penalty to the total distance.

By the way, if it's too complex, or you have no time nor motivation to add the Euclidean movement type I have an alternative making my request obsolete: Is it possible to make a new Addon with just the simple feature of displaying decimal digits per default when using the stock measuring tool? We use Meters, with 1.5m per grid. Foundry rounds the distance in some wierd way (not always mathematical rounding) so we have to hold SHIFT while measuring for precise decimal values. Additionally to CTRL for quick measuring or SPACE to move according to measurement. This finger-accrobatic with torturing the pinky is the main reason i'm using your addons or your Drag Ruler.

Best Regards from Austria

**Comment by manuelVo** [comment]
This is odd. Without Terrain Ruler, Euclidean should work just fine. Are you using v9? Maybe that's what breaks it - I haven't checked for v9 compatibility yet. Also: which game system are you using?

As for Terrain Ruler enabeld: there is an open request for Euclid support on gridded. Feel free to thumbs-up that issue. Seeng lots of people wanting a feature makes me more likely to implement it.

As a workaround, did you consider playing gridless. Euclidean distances are known to be working there.

**Comment by veithflo** [comment]
Issue exists in 0.8.9 and in newly upgraded v9. All modules are updated.

![grafik](https://user-images.githubusercontent.com/32668369/147390731-715a31df-f207-4cc2-9a2e-64fc6d0f6e6f.png)
![grafik](https://user-images.githubusercontent.com/32668369/147390736-809d86ee-55c7-4664-bcc9-5a65a1ecda04.png)
![grafik](https://user-images.githubusercontent.com/32668369/147390741-3ef1e6a8-5f1a-4493-8260-173c9520433e.png)
![grafik](https://user-images.githubusercontent.com/32668369/147390742-67164c0c-bf03-451a-80c3-cbe8a26e8279.png)
![grafik](https://user-images.githubusercontent.com/32668369/147390751-5f9b0d67-ebb3-45fc-aae8-7127ad139e5a.png)

Tested with following Minimal-Addons-Settings (and also with 100 more) ...
![grafik](https://user-images.githubusercontent.com/32668369/147390767-d8808d57-0dd6-4825-9106-59f72001cb37.png)
![grafik](https://user-images.githubusercontent.com/32668369/147390781-ef5f65e2-69ec-4f18-9e6c-28633d9f9c7d.png)

But still, its using 5/5/5 rule. But according to Pytagoras the middle part of the path should be sqroot((4,5²)x2)=6.36, not 4.50 (5/5/5) nor 6.0 (5/10/5).
![grafik](https://user-images.githubusercontent.com/32668369/147390786-d7613be7-307f-4e67-b597-0086d44f34a6.png)

But when looking into the code of measure.js from Terrain Ruler, there is no if-condition for "EUCL" only for for "pf2e" system and "5105" rule. Even the comment says, if no "pf2e" and no "5105" use "555".
![grafik](https://user-images.githubusercontent.com/32668369/147390803-50eaef37-b150-40ac-8df4-7fb00b1efaad.png)

I hope this explanations and details are helpfull. Nevertheless, I'll try a gridless map in the future, but i think we'll keep going with the grid.

**Comment by manuelVo** [comment]
I've given this a quick test. Without Terrain Ruler enabled, Euclidean measurement works fine for me - however the number is rounded to the next integer instead of showing the whole fractional measurement, which might be undesirable.

With 100 modules installed, this might likely be a conflict with another module. Please test if this bug persists for you if you disable all modules except Drag Ruler and socketlib.

**Comment by veithflo** [comment]
For the tests, there were only 9 modules active, and only 5 of them are not for Terrain Ruler or Drag Ruler. And these 5 are only for easier setup and module management. They won't interfere with anything regarding this issue.

Nevertheless, i've implemented a full euclidean support into your measure.js file with precise calculation and displaying of decimal places while still using all of your code. Just calculating and adding a surplus is all that has been done.
Link: https://github.com/manuelVo/foundryvtt-terrain-ruler/compare/develop...veithflo:patch-1

![grafik](https://user-images.githubusercontent.com/32668369/147393787-d498c8ce-915d-45ca-8e82-afc60f4fc4a1.png)
1.Step: Through Enemy, therefore 4.66m for euclidean + 1.5m for difficult terrain = 6.16m.
2.+3.Step: Only 4.66m for euclidean as no difficult terrain.
4.Step: 7.5m for stright non-euclidean + 1.5m for difficult terrain = 9m.

BTW: I took the calculation from .\Data\systems\dnd5e\module\canvas.js. There is also the line to chance the basic measure tool to not round by default. As explained, that was my initial problem and therefore i also have a fix for that now, even when it's obsolete now as your module also works now for me.

**Comment by manuelVo** [comment]
I've briefly skimmed the code you've linked and from what I can tell difficult terrain won't be calculated correctly for diagonal movement. Terrain Ruler has a code path that measures distances on gridless scenes. It should be possible to use the same code path for measuring euclidean on gridded scenes. But that's a discussion that we're better going to have in the Terrain Ruler repository, since all of that stuff is really handled by Terrain Ruler and Drag Ruler has no say in it whatsoever.
