### ISSUE TITLE
Ruler not working on gridless maps

### ISSUE THREAD

**Issue by KnoepfchenFulla** [manuelVo/foundryvtt-drag-ruler#137]
I have the following issue:

On gridless maps, the ruler is no longer working at all. I'm not sure when exactly this happened (we haven't had a fight in a while), but I remember it working before. If I turn on the grid in the scene configuration, the ruler is working again. Is this a known issue?

The system is The Dark Eye 2.5.1, on Foundry 0.8.9, hosted on The Forge.

**Comment by manuelVo** [comment]
Please disable all modules except Drag Ruler and socketlib and see if that resolves the issue.

**Comment by KnoepfchenFulla** [comment]
No, even doing as you said and disabling everything but those two did not resolve the issue, which is still present on gridless maps.
