### ISSUE TITLE
Conflict with Levels in V9

### ISSUE THREAD

**Issue by 9Volt1** [manuelVo/foundryvtt-drag-ruler#138]
Causes player tokens to be unable to move through walls that are on different levels than they are.  Walls function normally with regard to vision.

**Comment by manuelVo** [comment]
This also happens, when Token Movement via Crtrl+Measure+Spacebar is attempted. Since that is a function of core foundry, this is a bug in the Wall Height module. Please file an issue against [their Repository](https://github.com/erithtotl/wall-height/issues).
