### ISSUE TITLE
[Feature Request] Cancel Waypoints with Keyboard

### ISSUE THREAD

**Issue by mrkwnzl** [manuelVo/foundryvtt-drag-ruler#14]
Many laptops have TouchPads without physical left and right mouse buttons, but rely on multi-touch capabilities. In those cases, a right-clock would be a click with two fingers on the TouchPad.

On those machines, it’s impossible right now to cancel a waypoint, as that relies on the possibility to press the right mouse button while holding the left mouse button.

This could be resolved by having an additional keyboard key (that is, in addition to a right click) which would cancel a waypoint. My suggestion would be the x key. It’s near the space bar for easy access, works for most common keyboard layouts, and an X is a common sign for canceling the current process, making it intuitively easy to remember.

Thanks for considering!

**Comment by manuelVo** [comment]
Somewhat related issue: #4
