### ISSUE TITLE
Token Drag Vision is not handled correctly

### ISSUE THREAD

**Issue by dev7355608** [manuelVo/foundryvtt-drag-ruler#140]
In the path that skips core's `_onDragLeftDrop` we still need to reset vision to the initial location. Otherwise sight might be refreshed with the destroyed preview vision source still in the sight layer's sources. This seems to be harmless with just core (no errors at least), but it triggers an error if Perfect Vision is enabled.

```js
function onEntityDragLeftDrop(event) {
	const ruler = canvas.controls.ruler
	if (!ruler.isDragRuler) {
		ruler.draggedEntity = undefined;
		return false
	}

	// Reset vision back to the initial location
	if (game.settings.get("core", "tokenDragPreview")) {
		event.data.clones?.forEach(c => c._original.updateSource({ skipUpdateFog: true, defer: true }));
	}

	// When we're dragging a measured template no token will ever be selected,
	// resulting in only the dragged template to be moved as would be expected
	const selectedTokens = canvas.tokens.controlled
	// This can happen if the user presses ESC during drag (maybe there are other ways too)
	if (selectedTokens.length === 0)
		selectedTokens.push(ruler.draggedEntity);
	ruler._state = Ruler.STATES.MOVING
	moveEntities.call(ruler, ruler.draggedEntity, selectedTokens);
	return true
}
```

**Comment by manuelVo** [comment]
Good catch! In fact there appear to be several issues with Token Drag Vision in Drag Ruler (i never tested that setting, tbh) that need to be adressed (cancelling a drag is even broken without PV enabled)

**Comment by dev7355608** [comment]
FYI: In 9.245 Token Drag Vision parts were removed from `Token#_onDragLeftDrop`, and now there's the `Token#_onDragLeftCancel` that handles the Token Drag Vision logic.

**Comment by manuelVo** [comment]
Thanks for the heads-up. I've released a version with appropriate changes.
