### ISSUE TITLE
Waypoints Cause Incorrect Range Assignment for Diagonal Movement on v9

### ISSUE THREAD

**Issue by velara** [manuelVo/foundryvtt-drag-ruler#142]
![image](https://user-images.githubusercontent.com/74130268/148632304-cae6b3bb-63d2-42b2-9123-eb3d17b0301a.png)

It seems like the ranges for diagonal movement for systems like PF1e and PF2e that use 5-10-5 diagonal movement are being incorrectly calculated when waypoints are involved. As you can see from the image above when I measure four diagonal squares normally it correctly treats the distance 30 feet and assigns the second range colour to the final square. However, if a place a waypoint in certain positions it instead treats the last square as within the first range increment despite the character having 25 foot movement speed, and the ruler correctly showing the distance as 30 ft. 

The same phenomenon does not occur for characters with 30 feet movement speeds at the first range threshold, this coupled with the specificity of where the waypoint has to be be located to cause this error makes me suspect that the range increment calculation is treating the measurement between each waypoint as a new instance of diagonal movement. 

Numerically. In the 25 foot example I believe it is treating the squares as 5 - 10 - 5 (waypoint) 5  rather than 5 -10 - 5 waypoint 10. While in the 30 foot example it is treating the squares as 5 - 10 - 5 - 10 waypoint 5, thus correctly continuing the pattern despite beginning again. This seems to only effect the ranges not the measurements as both rulers correctly read 30 feet. 

**Reproduction:** I initially failed to reproduce this when it was first reported to me as a bug with the PF2e integration module, and I have not successfully reproduced it in existing or new scenes in my dev world. However, when I create a fresh world either with PF1e or PF2e the behaviour appeared. I don't believe it is an issue with my integration as it appears to effect both systems. I don't have any old-pf1e worlds to test in, but the bug does appear to only occur in worlds created under v9.

**Comment by manuelVo** [comment]
Is the difference between the worlds possibly that one has Terrain Ruler enabled and the other one doesn't?

**Comment by velara** [comment]
That seems very likely. 

I did not turn on terrain ruler on in the fresh worlds, but it would have been on in the development world. The person who reported the bug also didn’t use Enhanced Terrain layer, so they wouldn’t have had terrain ruler on.

**Comment by manuelVo** [comment]
Pew, that was quite challenging to fix. The fact that this bug has been around since the initial release of Drag Ruler and yet no one has discovered it until now is quite astonishing...
