### ISSUE TITLE
[Feature Request] Add range check

### ISSUE THREAD

**Issue by dmrickey** [manuelVo/foundryvtt-drag-ruler#16]
Show Drag Ruler had a super nifty feature where you can hit control and it'll measure the distance between the selected actor and the mouse cursor. This is ridiculously handy for quick-checking if someone was in range of a spell/attack/ability/etc. If it's within the scope of this project to add that feature in that'd be awesome.

**Comment by manuelVo** [comment]
Duplicate bug #6
