### ISSUE TITLE
Pathfinding Freeze/Lockup if Token is Trapped

### ISSUE THREAD

**Issue by JDCalvert** [manuelVo/foundryvtt-drag-ruler#165]
If a token is in an enclosed space (no way out), and you try to drag the token outside of that area while pathfinding, Foundry locks up entirely and the only thing you can do is kill the tab.

I've done a little bit of testing and found that in the opposite situation, when there is an enclosed space with no way in, the algorithm will correctly find that there's no way in and not draw a line or freeze up. I suspect this is because the algorithm works backwards from the target, and quickly runs out of options within that enclosed space. But when moving _to_ an enclosed space, every possible path is probably calculated.

**Comment by manuelVo** [comment]
Your diagnosis is correct. To guarantee that there is no possible path, the algorithm has to analyze every reachable square, which can take quite some time on large maps. The browser tab should unfreeze eventually, however waiting until that happens might not be feasible, depending on the size of the map.

I absolutely agree that freezing the browser tab is undesirable and the module should ensure that foundry responsive while computing paths, even on large maps.

Out of curiosity:
- How big is your map? (in number of suares/hexes, if it's gridded)
- Are you using a square, hex or gridless map?
  - If you're using square, what measurement style are you using? (5/5/5, 5/10/5)
- If you happen to know this: How many walls are on your map?

**Comment by JDCalvert** [comment]
Thanks for your reply. I'm actually having a go at tinkering with the algorithm myself to see if I can help. So far I (think) I've sorted your TODO where you said you didn't want to sort the `nextNodes` array every time. I've implemented a UniquePriorityQueue which makes `O(n)` inserts but it keeps itself in order and removes duplicate nodes.

My map is gridded, 48x48, so 2304 squares and I have 191 walls, so nothing too crazy. I'm also using levels a little bit, but from my testing so far the pathfinding works absolutely fine with that.

Also, just after writing the above, I found why it never returned for me. I didn't have walls around the outside of the map, and the algorithm only eliminates an edge if it's position is less than 0, not greater than the grid size! After walling around the outside, it only took a couple of seconds to work it out and then it ran smoothly using the cache.

So it looks like the fix might be as simple as checking that the neighbour is still within the map. I'll test it now and reply.

**Comment by manuelVo** [comment]
If you happen to have a fix I'll be happy to merge it.

Freezing for several seconds is still too much for my taste on a 48x48 map, but it's at least usable at that point. I'm considering porting the gridded algorithm to wasm to help out at that front. Probably there is even more to be done, because it feels like populating the cache should be much quicker on a map as small as yours. I'll run some benchmarks at some point to see if there are any areas for improvement. (I don't even know if re-sorting the list is indeed an issue, that TODO was simply created as an educated guess that this might not be ideal, but I don't know for sure).

**Comment by JDCalvert** [comment]
The linked pull request solves this issue and should generally improve the performance of the pathfinding a lot!
