### ISSUE TITLE
Can't Path find through one way Walls

### ISSUE THREAD

**Issue by MrChessur** [manuelVo/foundryvtt-drag-ruler#167]
Having an issue that when pathfinding through the "open side" of a one way wall. It attempts to path find around it even though you should be able to move through. If it's trapped, it just doesn't show the pathfinding tool and won't let you move out, even if you are GM(Except if using the M hotkey). It will path find through the "Closed side" but not around it, letting you go through the wall as GM or not move at all if you are a player. This may be related to a Issue #165, but I'm not sure so I a posting this as well.

**Comment by JDCalvert** [comment]
This is because pathing is done from the target back to the token, but collision testing is done the other way around. This would be fixed by #171, but if that doesn't go through, it can also be fixed by reversing the direction of the collision testing.
