### ISSUE TITLE
Does not seem to work with PF2e speed resource for calculating movement allowance

### ISSUE THREAD

**Issue by freyrrabbit** [manuelVo/foundryvtt-drag-ruler#17]
![image](https://user-images.githubusercontent.com/66050540/107147362-78a71900-6902-11eb-9f56-6d3588cdbcb5.png)

![image](https://user-images.githubusercontent.com/66050540/107147378-9c6a5f00-6902-11eb-941f-521119e4953a.png)

![image](https://user-images.githubusercontent.com/66050540/107147386-a8562100-6902-11eb-810f-575283786a4a.png)

![image](https://user-images.githubusercontent.com/66050540/107147409-c91e7680-6902-11eb-9aa3-a7755796c975.png)

Hopefully, the above show that the ruler is not correctly checking movement against speed limit for tokens. Tested in isolation.

Environment:
![image](https://user-images.githubusercontent.com/66050540/107147435-f408ca80-6902-11eb-98e9-db2426bb07c0.png)

**Comment by manuelVo** [comment]
The attribute starts at the token, so the correct value for pf2 is `data.data.attributes.speed.total`. Note that this will only work for player characters. A extension module for drag ruler is in the works that attempts to make npcs work as well is in the making. For more information about that ask in the pathfinder 2 channel on the foundry discord.
