### ISSUE TITLE
Allow players to remove single waypoints from their movement history

### ISSUE THREAD

**Issue by infias** [manuelVo/foundryvtt-drag-ruler#176]
I wanted to give players the ability to reset and go back for their movement if they mess up without me having to reset their movement history. The "Right click action" setting seemed to be what I wanted, but it only ever does the expected behavior for the "Cancel drag" never "Delete waypoint". Conversely, the "Create waypoint" seems to be working fine.

![image](https://user-images.githubusercontent.com/88762169/156251461-c18865cc-2612-46b9-8563-815bf1d39f08.png)

**Comment by manuelVo** [comment]
"Delete Waypoint" only removes waypoints that have been placed during the current drag. Waypoints in the movement history cannot be removed using the "Delete Waypoint" option. If you want to reset the movement history for a token, you can right-click the token in the combat tracker as GM and select "Reset movement history".

**Comment by infias** [comment]
Then I guess this is a feature request to have an option to "delete most recent waypoint" on right click. (maybe even another option for a reset on right click as well)

**Comment by gsterling** [comment]
I am also interessted in a way for players to remove their waypoint history. Ideally automatically moving to the last location each time until they reach their start.

**Comment by manuelVo** [comment]
Removing single waypoints can already be done by anyone (including players). Foundryvtt allows undoing a token movement by pressing Ctrl+Z. When doing so, Drag Ruler will remove the corresponding waypoint from the movement history.

**Comment by gsterling** [comment]
I just tested it and it does work. I just want to add for people not using a QWERTY layout, that you need to press the key, where the `Z` would be. So it's Ctrl+Y for german layouts.

Don't you use a german layout as well, @manuelVo?

**Comment by manuelVo** [comment]
Yes, that is a bug in Foundry core. The [Keyboard Layout module](https://foundryvtt.com/packages/keyboard-layout) allows you to specify your keyboard layout, which fixes the keyboard shortcuts.
