### ISSUE TITLE
[Major incompatibility] Foundry completely locksup/freezes 

### ISSUE THREAD

**Issue by Orionox** [manuelVo/foundryvtt-drag-ruler#178]
When using the module levels and drag ruler, if you put a token inside an enclosed area and try to drag it out of the area then foundry will completely freeze and require you to kill the task and restart. This appears to only happen with when pathfinding is enabled.

**Comment by manuelVo** [comment]
There is a known bug in the pathfinder that can cause foundry to freeze indefinitely in the circumstances you described. This can happen both with Levels enabled and disabled. There is also a known bug that can cause incorrect paths to be calculated when levels is enabled. Both issues should be gone with the next Drag Ruler version.

**Comment by manuelVo** [comment]
This should no longer be happening with Drag Ruler v1.13.0
