### ISSUE TITLE
[Issue] Drag Ruler overwrites regular ruler color when using the Measure Distance tool

### ISSUE THREAD

**Issue by Brimcon** [manuelVo/foundryvtt-drag-ruler#179]
Foundry 9.251/254
Drag Ruler 1.12.2
Only Drag Ruler and its dependencies Enabled.

I'm not sure if this is a limitation of the module or not but when a Player drags a token and Drag Ruler takes over the coloring, swapping back to the Ruler Tool keeps Drag Ruler's colors complete with the changing of colors 
GM Client:
![image](https://user-images.githubusercontent.com/7198283/156901253-5f119e91-5042-44b6-96cf-3db5c61f7ae5.png)

Player Client dragging the ruler.
![image](https://user-images.githubusercontent.com/7198283/156901267-56c92d0a-4f88-448c-a048-4c994a2f3b8d.png)

**Comment by manuelVo** [comment]
I cannot reproduce this. Please give a detailed step-by-step instruction on how to make this bug happen and also elaborate on what you'd expect to happen if the bug wasn't present.

**Comment by Brimcon** [comment]
Upon creating a fresh world, activate Drag Ruler and its dependancy then place a token down with speed (Using the Dragonborn Cleric sample Player from DND5e 1.5.7 compendium).
Make a new player in the User Management and give Ownership of that token to the player.
With either the Electron App or two browser windows open have one Gamemaster Client and a Player Client connect to the game.
Unpause the game to allow the Player client to drag their token. With Automatically start Measuring Enabled it will show the drag ruler colors as expected on both clients when the player starts dragging their token. (Default Cyan to Yellow to Red)
Have the player switch to the Measure Distance Tool (Ruler proper) and measure the distance between two points. Observe difference between Player Client and GM Client.
Player Client has their Player color in the Ruler, GM Client still shows the drag ruler colors for speed limitation as seen in the screenshots above.
