### ISSUE TITLE
Feature Request: Add API for recover the unit and grid distance calculated from this module

### ISSUE THREAD

**Issue by p4535992** [manuelVo/foundryvtt-drag-ruler#180]
Why am I asking for this feature? Let's start with the condition that practically everyone uses drag rulers, there are a lot of modules that use distance calculation mechanisms on their own _Arsm Reach, Item Piles, Levels, Innocenti Item loot and many other_.

There is literally a logic of "each for himself", this has created several problems (for me at least with Arms reach to meet certain requests) for compatibility between modules, also I am not smart enough to do the work you did with pathfinding, difficult terrain, elevation control, etc.

To try to synchronize all these modules with each other, is it possible to give the possibility via API to reuse the calculation of units and grids carried out by Drag Ruler? Something like this:

`dragRuler.getDistanceUnits(token, {x,y}) => number of unit distance e.g. 15 ft.`
`dragRuler.getDistanceGrids(token, {x,y}) => number of grid distance e.g. 3`

**Comment by p4535992** [comment]
My idea was to use the Drag ruler itself as a library as a multisystem api to handle terrain rulers, pathfinding, etc. from the same "access point", so that different modules agree on calculating distances with the same "procedure". Foundry's default method works, but sometimes it doesn't take into account some things.
But now I've realized that nobody's interested in it (apart from me), so you can close the ticket if you don't come up with brilliant ideas.

**Comment by manuelVo** [comment]
It took quite a while, but the Drag Ruler pathfinder is finally extracted into a dedicated library module: [routinglib](https://foundryvtt.com/packages/routinglib). If you're still interested in adding pathfinding to your module it should now be quite easy to grab routinglib as a (soft) dependency and just invoke its API to get a path calculated.

Are there any outstanding APIs that you were needing, or can I close this issue?

**Comment by p4535992** [comment]
sure sorry totally forgot about this.... ty for the hard work
