### ISSUE TITLE
Conflict with DF Template Enhancements: `MeasuredTemplate` no longer references `TemplateLayer.gridPrecision`

### ISSUE THREAD

**Issue by flamewave000** [manuelVo/foundryvtt-drag-ruler#181]
The entity movement controls are not ~~being wrapped by libWrapper and are also not~~ referencing the `TemplateLayer.gridPrecision` property. This causes a conflict with [DF Template Enhancements](https://github.com/flamewave000/dragonflagon-fvtt/blob/master/df-templates) which adjusts the [grid precision for grid intersection snapping](https://github.com/flamewave000/dragonflagon-fvtt/blob/master/df-templates/src/SnapIntersect.ts).

https://github.com/manuelVo/foundryvtt-drag-ruler/blob/44efabc65675763bdfee25f26741b9f25653897e/js/util.js#L93-L114

Also, I'm not sure if performing your own grid snapping logic is necessary as FoundryVTT provides the following function for exactly this:
```js
// HexagonalGrid and SquareGrid both extend this class
class BaseGrid {
...
/**
	 * Given a pair of coordinates (x1,y1), return the grid coordinates (x2,y2) which represent the snapped position
	 * Under a "gridless" system, every pixel position is a valid snapping position
	 *
	 * @param {number} x          The exact target location x
	 * @param {number} y          The exact target location y
	 * @param {number|null} [interval]  An interval of grid spaces at which to snap.
	 *                                  At interval=1, snapping occurs at pixel intervals defined by the grid size
	 *                                  At interval=2, snapping would occur at the center-points of each grid size
	 *                                  At interval=null, no snapping occurs
	 *
	 * @return {{x, y}}           An object containing the coordinates of the snapped location
	 */
	getSnappedPosition(x, y, interval=null);
...
}

const destination = canvas.grid.grid.getSnappedPosition(x, y, gridPrecision);
```

**Comment by manuelVo** [comment]
I'm able to verify the conflict between the modules. However, I'm unsure to what you're referring about when you're saying
> The entity movement controls are not being wrapped by libWrapper

Can you point out the code locations where this is the case?

**Comment by flamewave000** [comment]
My apologies, when I was searching where you implemented the template feature I think I was on an old commit before you converted to libWrapper. I initially searched for the commit whose message said it implemented to template feature ([Implement measurement template support](https://github.com/manuelVo/foundryvtt-drag-ruler/commit/acd2e74064e67bd43a0eea4be51c7aef030042a5)) which I realise now was actually a very old commit.

I've redacted that part of the original ticket.

**Comment by flamewave000** [comment]
Hey, I just checked your commit, I believe you might get `NaN` on gridless scenes when you call `getSnappedPosition()`

**Comment by manuelVo** [comment]
Thanks. `getSnappedPosition` is indeed behaving differently on gridless than I expected

**Comment by flamewave000** [comment]
Yeah I saw that when I was trying the above solution I proposed. Internally it's doing a Divide-by-Zero when on a Gridless scene which causes the X,Y to be NaN.
