### ISSUE TITLE
libWrapper warning - "Module drag-ruler did not chain the wrapper for 'Token.prototype._onDragLeftDrop'."

### ISSUE THREAD

**Issue by Doresain** [manuelVo/foundryvtt-drag-ruler#184]
I haven't noticed any adverse effect. but noticed this popup from libWrapper on token drag today:

![image](https://user-images.githubusercontent.com/26096062/159157393-5bdd5412-bea4-4e32-8d98-8b7cf6a54391.png)

**Comment by manuelVo** [comment]
This warning only informs you that libwrapper is unable to guarantee that there will be no conflict. This warning showing up does not indicate that there are any issues, and it's in fact pretty normal. Unless you notice any ill effects, it's safe to ignore this waring.

I'll close the issue, but feel free to reopen it should you notice any adverse effects.
