### ISSUE TITLE
[Feature request] Chronicles of Darkness 2e Compatibility

### ISSUE THREAD

**Issue by lucaspicerni** [manuelVo/foundryvtt-drag-ruler#186]
In the [CofD system](https://gitlab.com/MarlQ/mta), only the Ephemeral character sheet integration is not working with Drag Ruler.

**Comment by lucaspicerni** [comment]
Sorry, I didn't expressed myself precisely. In fact the integration with the system is working correctly. In this system, just like in DnD there are PCs, NPCs and vehicles, there are different types of character sheets (more specifically, 'characters' and 'ephemeral'). However, each character sheet uses a different specification for movement. I'm using the following attribute:

actor.data.data.derivedTraits.speed.value

This way it works for all 'characters', but not for 'ephemeral'. So a possible solution would be to implement a configuration that allows a different attribute for each type of character sheet.

**Comment by lucaspicerni** [comment]
From what I could understand from the reading, does this require me to change the system code to use the API? Or should I change the API code? I am completely ignorant of programming.

**Comment by manuelVo** [comment]
Hmm, not being able to program doesn't help, but I guess it should still be doable. You would either need to change the system code or create a new module that uses the API code. Both methods work equally well. If you were to create a new module, you could basically copy&paste the exmample from the api documentation into a new module and then adjust it according to your needs.
