### ISSUE TITLE
Inconsistent Walk/Dash/Run Indicators

### ISSUE THREAD

**Issue by erandisvol** [manuelVo/foundryvtt-drag-ruler#189]
The color indicators for an actor's speed is inconsistent in the Pathfinder 1e system. When an actor is dragged east or south, it measures correctly, but north and west, it's one space shorter than it should be. The numerical measurement displayed on the dragging action is still accurate. This occurs on different speeds, I've tested with 20, 30, and 60 ft.

I'm running Foundry V9 Build 255, using the Pathfinder 1e system version 0.80.15, using Drag Ruler 1.12.7. The system diagonal measurement settings are on the default 5/10/5 setting
![East](https://user-images.githubusercontent.com/74384720/162541920-8191be63-4928-4c64-8976-db433532458b.png)
![West](https://user-images.githubusercontent.com/74384720/162541938-68945b31-2450-4ec8-8202-5734fa9915bd.png)
![Northwest](https://user-images.githubusercontent.com/74384720/162541962-d14e1010-5061-4ff2-bcc7-23846b374fdd.png)
.

**Comment by manuelVo** [comment]
Until this is fixed, a workaround would be to install and enable the Terrain Ruler module. With the terrain ruler module enabled, this bug does not occur.
