### ISSUE TITLE
Hide rotation arrows in HUD for tokens with Lock Rotation

### ISSUE THREAD

**Issue by eggdropsoap** [manuelVo/foundryvtt-drag-ruler#192]
On tables with mixed token styles (like top-down monsters and portrait-style PCs) it's useful to select Lock Rotation in the token configuration for the tokens that shouldn't rotate. With direction arrows enabled in Drag Ruler, this creates a UX problem where players with locked-rotation tokens see the arrows but they do nothing, frustrating discovery UX, and raising the usability barrier of Foundry a little bit higher.

Drag Ruler should hide the arrow buttons on the token's HUD for locked-rotation tokens, even if “Direction arrows in Token HUD” is set On. This will make the appearance of the token HUD arrows sensitive to context by removing UI elements that are non-functional for that token.

**Comment by manuelVo** [comment]
Drag Ruler doesn't add any direction arrows to foundry. Maybe they are coming from a different module?

**Comment by eggdropsoap** [comment]
I'm sorry! You're right, this should be for TouchVTT. I had both repos open to investigate compatibility and just… forgot which one I was thinking of when I submitted this. Thanks for the quick catch. I'll submit this where it belongs!
