### ISSUE TITLE
Error: Selecting or moving a token causes an error when trying to start background caching (develop branch only)

### ISSUE THREAD

**Issue by schultzcole** [manuelVo/foundryvtt-drag-ruler#196]
This issue does not affect the version of drag ruler that has been deployed (1.12.8), only what is on the develop branch.

When controlling or moving a token, the function `startBackgroundCaching`  throws an error because the cache layer doesn't contain an entry for the token's position. This doesn't seem to cause any problems in the outwardly visible behavior, but it does show the error in the console and presumably the benefits of the background caching aren't being used because of this error.

![Foundry_Virtual_Tabletop_4gVMx1hS6N](https://user-images.githubusercontent.com/1226888/165875489-f91e5ee0-ef4c-4b03-bd1b-2d6f8f975b73.png)

It seems that this stems from commit 2979e86201f411003d6b09fa6fa489fab3727bf1 by @JDCalvert which is present on develop, but not master.

**Comment by manuelVo** [comment]
This appears to only happen on gridless scenes. Can you confirm that observation?

**Comment by schultzcole** [comment]
Correct, only on gridless scenes.
