### ISSUE TITLE
Conflict with FoundryVTT Wall Height Module

### ISSUE THREAD

**Issue by lupinelegend** [manuelVo/foundryvtt-drag-ruler#214]
With the [Wall Height module](https://github.com/theripper93/wall-height) enabled, Drag Ruler doesn't work as expected for players. Drag Ruler works fine for the GM.

Players are able to drag a token and set waypoints as normal, but when they release the left mouse button, the token does not move along the path. Pressing 'SPACE' to "Move Along Measured Ruler" does not work either.

Each time a player tries to move their token, errors appear in the console at DragRulerRuler.moveEntities - [screenshot here](https://imgur.com/a/KRPyR6G).

**Comment by manuelVo** [comment]
Fixed by ff9b187
