### ISSUE TITLE
Bug with SWADE system joker's wild

### ISSUE THREAD

**Issue by lipefl** [manuelVo/foundryvtt-drag-ruler#215]
Everytime you move a combatant that has a joker, the system Joker's Wild is activated. It should be activated only when the joker is dealt. This doesn't happen if drag ruler is inactive. 
System: Savage Worlds Adventure Edition

**Comment by manuelVo** [comment]
Does this happen when all other modules except Drag Ruler (and it's dependency socketlib) are disabled?

If so, please give detailed instructions on how to reproduce this using a fresh SWADE world. I don't know the SWADE game system, so I don't know what "having a joker", "activating joker's wild" and "dealing a joker" mean in a Foundry context.

**Comment by brunocalado** [comment]
> Does this happen when all other modules except Drag Ruler (and it's dependency socketlib) are disabled?
> 
> If so, please give detailed instructions on how to reproduce this using a fresh SWADE world. I don't know the SWADE game system, so I don't know what "having a joker", "activating joker's wild" and "dealing a joker" mean in a Foundry context.

Reproduce steps:
1. create 2 users
2. add pcs to them
3. log as these 2 users
4. start a combat with them
5. add 2 npcs to the combat
6. advance the combat until a pc receive a joker. joker is card, is something like Blk J or Red J. When this happen the pcs will receive a benne (image 2). They should receive only one each. BUT, if you move the token of the pc they will receive more. This only happens with drag ruller on

image 1
![image](https://user-images.githubusercontent.com/4999783/177995323-c363c864-bb70-480a-ae62-1243f00c9d62.png)

image 2
![image](https://user-images.githubusercontent.com/4999783/177995711-9cdb63e5-7b6f-464b-9c4c-bdbd3b0a6020.png)

**Comment by FloRad** [comment]
This is one of unfortunate times when the interplay of two things causes an issue. The trigger conditions for the Joker's Wild rule in the system were too loose. I've tightened them up in system version 1.1.8, so this ticket can probably be closed since Drag Ruler wasn't the cause.
