### ISSUE TITLE
API to report distance moved

### ISSUE THREAD

**Issue by n0q** [manuelVo/foundryvtt-drag-ruler#22]
I'd find it very useful if the API had some mechanism (promise/await?) to report the total distance a token moved. This would allow a system to dynamically adjust the color banding to account for smaller moves made during a turn.

Thanks for all your work. This had rapidly turned into an absolute "must have" module.

**Comment by manuelVo** [comment]
Thanks for the kind words. I have something along those lines planned for 1.4.0 (if nothing more urgent pops up until then), so stay tuned!

**Comment by manuelVo** [comment]
This was implemented in 35624a37aa07670ba69095a03f5c8c0857e123cb.
