### ISSUE TITLE
Error with Foundry v10

### ISSUE THREAD

**Issue by Kharmans** [manuelVo/foundryvtt-drag-ruler#221]
When use the module with Foundry v10, the Configurations don't open. The error bellow is showed in the console.

![image](https://user-images.githubusercontent.com/112586547/187790307-35f8d3e0-d308-475f-a991-75d041726485.png)

**Comment by r-valyar** [comment]
Second that. Module does not work in v10

**Comment by bearsy1** [comment]
Third this! Your module, your work, makes games in foundry that much better. <3 
Would be great to be able to use this in v10. Dragging a token and _not_ having that measuring line for its walking speed feels weird since having used this from the get-go from v9.

**Comment by minakitty** [comment]
Fourth here with PF1e. The has always been a pretty critical module for me and my players, gonna be a bit awkward without it

**Comment by ZeroXNoxus** [comment]
Fifth here, it's really a nice feature to keep track of movement! Love the module, would be a shame if it would be unavailable for the next session.

**Comment by w1face** [comment]
6th here.  We go gridless, and without this module that become almost impossible.  This makes the game not tied to a gridded battlemap viable! :)

**Comment by RoyRandom** [comment]
and a 7th here. I wont switch to foundry v10 until I have this module. I like it so much i would pay for it.

**Comment by jbsolter** [comment]
8th here. switching between the "Measure Distance" and "Select Tokens" icon is such a pain when you just want to move a few grid spaces.

**Comment by manuelVo** [comment]
I've got good news and bad news.

Good news is that this module will be ported to Foundry 10.

Bad news is that there's a lot to do for the v10 port of Drag Ruler, which is the reason why it'll take several weeks until a v10 compatible version of Drag Ruler is going to be available.

**Comment by esheyw** [comment]
Sending good vibes, friend, I use like half a dozen of your mods, thanks for all you do :)

**Comment by mattd** [comment]
I have _no_ problem waiting to upgrade to v10 if it means I get to use this module. Take the time you need! (From a dev that loves your module.)

**Comment by TheMathKing** [comment]
This is such an essential feature that I am perplexed that core Foundry doesn't make it a default feature.

**Comment by RuebenMF** [comment]
> This is such an essential feature that I am perplexed that core Foundry doesn't make it a default feature.

couldn't agree more, truly a must-have module!

**Comment by crnormand** [comment]
Seconded!   This module is invaluable to the GURPS Game Aid (https://foundryvtt.com/packages/gurps).   If there is anything we can do to help, please reach out!

**Comment by Traumi** [comment]
For people who can't wait for the update, I made a fix that would work until an official update, it have some minor bugs but I tried to make it the more usable as possible (I'm not an experimented developer)
In any case I would recommend you to switch to the original project as soon as it will be updated
[Link to the fix](https://github.com/Traumi/foundryvtt-drag-ruler)

**Comment by morgan613** [comment]
@Traumi first off thank you very much for doing this! Second off, I installed your version (following the directions) but it seems that there is an error with pathfinding. For the GM I can see "allow pathfinding for players" in my settings but neither for the GM nor for the player is there an option to turn pathfinding on and it simply won't try to pathfind around walls. I get these two errors from my log that might explain the issue. 

> Error: You are accessing the Scene#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
>     at logCompatibilityWarning (commons.js:1245)
>     at Function._logV10CompatibilityWarning (commons.js:6166)
>     at Scene.get data [as data] (commons.js:6066)
>     at Ruler.highlightMeasurementNative (foundry_imports.js:404)
>     at Ruler.measure (foundry_imports.js:389)
>     at Ruler.measure (ruler.js:68)
>     at Ruler.scheduleMeasurement (foundry_imports.js:215)
>     at Ruler.onMouseMove (foundry_imports.js:207)
>     at Token5e.onEntityLeftDragMove (main.js:163)
>     at Token5e.onEntityLeftDragMoveSnap (main.js:156)
>     at Token5e.🎁Token.prototype._onDragLeftMove#0 (libWrapper-wrapper.js:187)
>     at MouseInteractionManager.callback (foundry.js:27633)
>     at MouseInteractionManager._handleDragMove (foundry.js:27990)
>     at MouseInteractionManager._handleMouseMove (foundry.js:27962)
>     at e.a.emit (index.js:202)
>     at r.dispatchEvent (interaction.min.mjs:8)
>     at r.processPointerMove (interaction.min.mjs:8)
>     at t.recursiveFindHit (interaction.min.mjs:8)
>     at t.findHit (interaction.min.mjs:8)
>     at r.processInteractive (interaction.min.mjs:8)
>     at r.onPointerMove (interaction.min.mjs:8)

and 

> Error: You are accessing Actor5e#data which has been migrated to Actor5e#system
> Deprecated since Version 10
> Backwards-compatible support will be removed in Version 12
>     at logCompatibilityWarning (commons.js:1245)
>     at Function._logDataFieldMigration (commons.js:6155)
>     at Object.get (commons.js:6119)
>     at getProperty (commons.js:1707)
>     at GenericSpeedProvider.getRanges (speed_provider.js:140)
>     at getRangesFromSpeedProvider (api.js:82)
>     at Ruler.dragRulerGetColorForDistance (ruler.js:180)
>     at Ruler.highlightMeasurementNative (foundry_imports.js:425)
>     at Ruler.measure (foundry_imports.js:389)
>     at Ruler.measure (ruler.js:68)
>     at Ruler.scheduleMeasurement (foundry_imports.js:215)
>     at Ruler.onMouseMove (foundry_imports.js:207)
>     at Token5e.onEntityLeftDragMove (main.js:163)
>     at Token5e.onEntityLeftDragMoveSnap (main.js:156)
>     at Token5e.🎁Token.prototype._onDragLeftMove#0 (libWrapper-wrapper.js:187)
>     at MouseInteractionManager.callback (foundry.js:27633)
>     at MouseInteractionManager._handleDragMove (foundry.js:27990)
>     at MouseInteractionManager._handleMouseMove (foundry.js:27962)
>     at e.a.emit (index.js:202)
>     at r.dispatchEvent (interaction.min.mjs:8)
>     at r.processPointerMove (interaction.min.mjs:8)
>     at t.recursiveFindHit (interaction.min.mjs:8)
>     at t.findHit (interaction.min.mjs:8)
>     at r.processInteractive (interaction.min.mjs:8)
>     at r.onPointerMove (interaction.min.mjs:8)

My understanding of coding is limited but given what the warning was saying and looking into the files a bit it looks like the old way of referencing some things (e.g., " scence.data.[instert whatever here] and actor.data") should be changed, maybe? Hopefully this helps! Thank you very much for your contribution to this amazing project.

**Comment by morgan613** [comment]
@Traumi nvm I found the issue. In the "settings.js" autoPathfinding setting is commented out (copy and paste of relevant code below). Did you do this on purpose? Is pathfinding broken?

> /*game.settings.register(settingsKey, "autoPathfinding", {
> 		name: "drag-ruler.settings.autoPathfinding.name",
> 		hint: "drag-ruler.settings.autoPathfinding.hint",
> 		scpoe: "client",
> 		config: early_isGM() || game.settings.get(settingsKey, "allowPathfinding"),
> 		type: Boolean,
> 		defualt: false,
> 	});*/

**Comment by Traumi** [comment]
@morgan613 Yeah, I had some troubles with pathfinding so I removed it while I'm looking on how to fix it (it prevent settings to open so it was a bit annoying) but I don't promise anything on it, that's why I said that when a true fix will be released it would be better to use it 😅
Those two warning are because they changed some Objects format, I fixed a lot of them but not those two, I will look for it ;)

**Comment by morgan613** [comment]
Ahhh okay, that makes sense! Thank you very much for the work you have done!

**Comment by Traumi** [comment]
@morgan613 I removed the lasts depreciations warning in the last push so now the project is (theorically) warnings free, still have to download it manually because I basically planned to make it as a one version only xD, I'll take a look on the pathfinding part now, if I manage to fix it too I will post a message here ;)
Thanks for your feedback :)

**Comment by morgan613** [comment]
Oh, wonderful! Thank you very much @Traumi!

**Comment by manuelVo** [comment]
Please move discussions about issues in the fork to the fork's GitHub repository. @Traumi feel free to still post updates about new versions of your fork here, so people have a chance to see them.

**Comment by Fridan99** [comment]
Traumi has posted a “temporal” fix…

https://github.com/Traumi/foundryvtt-drag-ruler

**Comment by Traumi** [comment]
Hello, I'm coming with some news, nothing new about the pathfinding part (I try, I try xD) 
But I just pushed a new part where I fixed an annoying bug where tokens couldn't move if they had a part merged in a wall, so you'll just have to download the new version, if you find some bugs on it, just open an issue on my fork in order to not spam here ;) (The link to the package can be found in the previous messages)

**Comment by SirAron111** [comment]
Hope this gets ported to v10 soon. It's such a key module they added pings, but they should have also added this as a key function. My players started to get confused when it disappeared from the game after I updated.

**Comment by CaosFR** [comment]
@Traumi Thanks for the fix until @manuelVo update it's module (happy dev).

**Comment by manuelVo** [comment]
Drag Ruler v1.13.0 has just been released, which supports Foundry v10.

**Comment by CaosFR** [comment]
Thanks :)

**Comment by SirAron111** [comment]
Nice now i have them all....fades away.
