### ISSUE TITLE
Is this module abandoned?

### ISSUE THREAD

**Issue by ZeroXNoxus** [manuelVo/foundryvtt-drag-ruler#222]
I'm wondering if any development will happen after the v10 Foundry update. This module is really useful to visualize distance in a turn and it would be very disapointing to lose this feature!

**Comment by emwhalen** [comment]
No, it is not abandoned, but the update will take some time.
https://github.com/manuelVo/foundryvtt-drag-ruler/issues/221#issuecomment-1236386099

**Comment by maxerature** [comment]
Any way I can help make it go faster?

**Comment by weepingminotaur** [comment]
Eagerly looking forward to this module becoming v10-compatible!
