### ISSUE TITLE
[System request] Splittermond

### ISSUE THREAD

**Issue by gsterling** [manuelVo/foundryvtt-drag-ruler#224]
Hey,
since Splittermond had an update, the old path I added months ago to the generic system, was not working anymore. So I did some digging and corrected it. To spare others the hassle I thought it'd create a PR for you.

https://github.com/manuelVo/foundryvtt-drag-ruler/pull/223

Is anything missing?

Your module is such an integral part of my Foundry experience, I will keep it up to date as long as I play it or it will become part of the core system.

**Comment by manuelVo** [comment]
The PR is merged and will be released as part of Drag Ruler v1.13
