### ISSUE TITLE
Token size doesn't reset to medium for movement

### ISSUE THREAD

**Issue by njgiac** [manuelVo/foundryvtt-drag-ruler#227]
I'm having an issue in PF2e with Drag Ruler where when the Enlarge effect is applied to a creature and then later removed, Drag Ruler still treats the token as size Large in that it won't let them move (via Drag Ruler movement) into tight spaces like a 5' wide hallway. If this could be fixed in the V10 implementation that would be excellent. Thanks

**Comment by manuelVo** [comment]
Im not familiar with pf2. Please elaborate how the etangle condition relates to the token size.

**Comment by njgiac** [comment]
Oh, it's Enlarge not Entangle, so a spell effect that (among other things) makes a creature and its token temporarily become Large (10'x10' instead of 5'x5')

**Comment by njgiac** [comment]
I tested it just now and that's correct. When pathfinding is turned off this doesn't happen
