### ISSUE TITLE
v10 Compatibility and release

### ISSUE THREAD

**Issue by manfred7168** [manuelVo/foundryvtt-drag-ruler#229]
Hi, when do you expect a v10 compatible release of drag ruler?
On the Foundry project page https://foundryvtt.com/packages/drag-ruler Drag Ruler is still marked as v9 module.
And the developer of PF2e drag ruler integration will start as soon as drag ruler is v10 ready...

**Comment by p4535992** [comment]
ON fvtt10, there is a exception when i click on the "Manage settings" button, it's seem the setting "autoPathfinding" is  undefined for some reason ?
After a bit of debug i found  out the origin is this module.

Core Version: 10.287
System: dnd5e 2.0.3 (Atropos) 
drag-ruler 1.12.8 (Manuel Vögele)

![img](https://i.imgur.com/iqnS0sT.png)
![img](https://i.imgur.com/oKqiZTE.png)

**Comment by JDCalvert** [comment]
@p4535992 this has been reported in several other issues. The module has not yet been updated to v10, but it is being worked on.

**Comment by manuelVo** [comment]
Drag Ruler v1.13.0 has just been released, which supports Foundry v10.
