### ISSUE TITLE
foundry hud weblate

### ISSUE THREAD

**Issue by eunaumtenhoid** [manuelVo/foundryvtt-drag-ruler#230]
hi, is it possible to add your mods to foundry hud weblate for us to translate or update the translation faster? https://weblate.foundryvtt-hub.com/

**Comment by manuelVo** [comment]
I've added Drag Ruler to Weblate. For now, it's an evaluation period. Whether I'll keep it there depends on the quality of the PRs that will be posted by the weblate bot.
