### ISSUE TITLE
Module Manifest Error

### ISSUE THREAD

**Issue by lucky-trill** [manuelVo/foundryvtt-drag-ruler#233]
Installing Drag Ruler using the module.json here in the git worked fine, but when I initially tried to install it via Foundry's installer, it threw the following error:

Error: Unable to load valid module manifest data from "https://raw.githubusercontent.com/manuelVo/foundryvtt-drag-ruler/v1.30.0/module.json" . . .

And that manifest link goes to a 404 (and doesn't match the module.json here).

**Comment by manuelVo** [comment]
There was a typo in the manifest. It should be fixed now.
