### ISSUE TITLE
Drag Ruler not showing in SWADE

### ISSUE THREAD

**Issue by Deadlander** [manuelVo/foundryvtt-drag-ruler#235]
Very happy with the release, however, when using Drag Ruler with Elevation Ruler and/or Terrain Ruler, the Drag Ruler is not making an appearance.  It causes an unknown error with Elevation Ruler, and the following error with Terrain Ruler:
![image](https://user-images.githubusercontent.com/13036735/195642109-36f42cd5-30bd-4049-81b4-2786fcdf4e89.png)
Everything is updated to v10.

**Comment by manuelVo** [comment]
Which version of Enhanced Terrain Layer do you have installed?

**Comment by Deadlander** [comment]
10.4

**Comment by manuelVo** [comment]
Are you using a word that has been ported from Foundry v9 to Foundry v10? I'm suspecting that there is some terrain on your scene that might not have been migrated over properly. Please test if this issue occurs on a new, empty scene. If it doesn't occur there please make a copy of the scene that has this bug and delete terrain one by one and retry if this bug persists, until know which terrain is causing this issue. If you were able to identify a piece of terrain, try if replacing it with a new piece of terrain in the original map will fix your issue.

**Comment by manuelVo** [comment]
It turns out that Terrain Ruler is currently broken on gridless scenes in all game systems. I've opened an issue in the Terrain Ruler repository about this: https://github.com/manuelVo/foundryvtt-terrain-ruler/issues/36
