### ISSUE TITLE
Tokens snap incorrectly on hexagonal grids

### ISSUE THREAD

**Issue by BoltsJ** [manuelVo/foundryvtt-drag-ruler#236]
On hexagonal grids, tokens with an even size are snapped incorrectly.

Steps to reproduce:
1. Create a scene using a hexagonal grid
2. Create a token with size 2×2
3. Move the token
4. The token snaps the center of the token to a cell center, causing it to be misaligned from the grid.

No console errors are reported.

![image](https://user-images.githubusercontent.com/182554/195654623-62ff7de7-2333-484b-8adc-21c989ed8e0a.png)
![image](https://user-images.githubusercontent.com/182554/195655225-0687fe65-d94c-4857-ba47-6906cff00b85.png)

**Comment by BoltsJ** [comment]
I noticed you added the module conflict label, but this is with no other modules

**Comment by manuelVo** [comment]
I wasn't aware that Foundry started supporting larger than 1x1 tokens on hex grids, so I expected the Hex Size Support module to be enabled.

**Comment by manuelVo** [comment]
This has been fixed in a9c15d779
