### ISSUE TITLE
Error in getAltOrientationFlagForToken when hex-size-support is not installed.

### ISSUE THREAD

**Issue by BoltsJ** [manuelVo/foundryvtt-drag-ruler#241]
If hex-size-support is not installed, this line throws an error. https://github.com/manuelVo/foundryvtt-drag-ruler/blob/develop/src/util.js#L67

`get(…).api` should be optional chained to `get(…)?.api` to support the case where hss isn't installed at all

**Comment by manuelVo** [comment]
Oops. Thanks!
