### ISSUE TITLE
Dozens to HUNDREDS of warnings in console every time you drag a token

### ISSUE THREAD

**Issue by GambetTV** [manuelVo/foundryvtt-drag-ruler#249]
I was noticing a bit of a slowdown since upgrading to v10, and I think I tracked it down to your module. Right now if I drag a token, I seem to get dozens of warnings in the console every second. The warnings are all variations of "Error: You are accessing Actor5e#data which has been migrated to Actor5e#system Deprecated since Version 10". With hundreds of errors popping off every time I drag a token from point A to B, I think this might be the cause of a lot of Foundry issues.

**Comment by manuelVo** [comment]
Yes, tons of these warnings can indeed cause slowdown. Please check your speed provider settings and make a screenshot of the speed provider settings

**Comment by GambetTV** [comment]
Ah, that was it actually. Speed Attribute was set to actor.data.data.attributes.movement.walk. When I checked a different world, it was set to actor.system.attributes.movement.walk. Must have been a world import issue when I upgraded to v10.

**Comment by manuelVo** [comment]
The default of that value has changed in v10. `actor.data.data.attributes.movement.walk` is the old value, so I suppose the imported world didn't pull in the new default.
