### ISSUE TITLE
Diagonal steps

### ISSUE THREAD

**Issue by Alexsist** [manuelVo/foundryvtt-drag-ruler#250]
Please add an option in the settings, check the box so that the cells are counted diagonally by 2. When 2 steps diagonally is 4 cells

**Comment by manuelVo** [comment]
Drag Ruler uses the measuring method that the regular Foundry ruler provides. If you need a different measuring method you have 2 options:
- If the measurement method is mandated by the game system you're using, please file an issue with the developer of that game system to provide the correct measuring methods (or to provide options, like DnD 5e does).
- If you want to use a measurement method other than one provided by your game system, you can write a small module that provides your preferred measuring method.
