### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by dev7355608** [manuelVo/foundryvtt-drag-ruler#255]
https://github.com/manuelVo/foundryvtt-drag-ruler/blob/a65ff4ddb4d3e5da3efd7d6049f4575515462a01/src/compatibility.js#L21

I randomly spotted the typo browsing the code. No idea what the implications of this typo are.

**Comment by manuelVo** [comment]
Good catch. It probabaly won't cause any issues, since the value will probably be undefined and thus evaluate to false in all cases, but it's worth fixing it anyway
