### ISSUE TITLE
[Issue] Pathfinding doesn't work

### ISSUE THREAD

**Issue by CixrTyx** [manuelVo/foundryvtt-drag-ruler#259]
Pathfinding is not currently working.  When turned on for Pathfinding for Players, and Use Pathfinding as Default; dragruler no longer works at all.  Can you fix this?

**Comment by CixrTyx** [comment]
Drag Ruler pathfinding doesn't work will you be updating this anytime soon?

**Comment by manuelVo** [comment]
Since caewok has mentioned this from one of his issues: Does this issue happen with all modules except Drag Ruler and routinglib disabled?

**Comment by caewok** [comment]
Fixed in Light/Sound Mask v0.6.4. The issue was that Light Mask was checking edges against a cache, but the edges passed to the sweep from pathfinder were not constructed the same as the typical edge used in sweep, so it was erroring out. A simple check avoids the issue.
