### ISSUE TITLE
Warhammer 4ed 

### ISSUE THREAD

**Issue by Ryach** [manuelVo/foundryvtt-drag-ruler#267]
Could you please add integration for Warhammer 4ed System:
https://foundryvtt.com/packages/wfrp4e

**Comment by manuelVo** [comment]
Drag Ruler contains no game system specific code. Game System integrations need to be provided either by the game system itself or by a third party module via [Drag Ruler's API](https://github.com/manuelVo/foundryvtt-drag-ruler#api).
