### ISSUE TITLE
Colour/Movement mismatch

### ISSUE THREAD

**Issue by YokaiGer** [manuelVo/foundryvtt-drag-ruler#27]
The colour calculation is starting at the grid where the token is on. So my landing grit has the wrong colour. If my character is allowed to make 6 movements the 7th field should have an other colour or? But now the 6th field have an other colour.

**Comment by YokaiGer** [comment]
Or is this problem caused by the module PF2E Drag Ruler Integration?

**Comment by manuelVo** [comment]
Please provide a screenshot of this problem occuring. Additionally please tell me how much movement the character has according to the character sheet. With that information I can investigate further.

**Comment by YokaiGer** [comment]
I tried to repeat the issue and found out it's because I changed the settings to metric. 5ft. = 1,5m. If I give the character movement of 6 or an other straight number its finde but if its with x,5. Its not working.

**Comment by manuelVo** [comment]
Am I correct to assume that the measured distance is 5m even tough you were only moving the token by 4,5m?

**Comment by manuelVo** [comment]
This is a bug within the PF2E Drag Ruler Integration. I've informed the module author about this issue.
