### ISSUE TITLE
dragRulerStart() broken under v11.297

### ISSUE THREAD

**Issue by n0q** [manuelVo/foundryvtt-drag-ruler#270]
**OS**: Linux
**Systems Tested**: D&D5e, Hackmaster, Wicked Ones
**Foundry Version**: 11.297 (Testing 2)

Drag-Ruler no longer functions. It's the same error messages on every system. There's no measurement and the token does not move.

**Steps to Reproduce**:
1. Drag token.

![image](https://github.com/manuelVo/foundryvtt-drag-ruler/assets/7948363/c0446c09-8ba4-4fe1-8f1d-74f7ba355d9c)

**Comment by n0q** [comment]
Confirmed broken under v11 stable, as well. Seems like the issue is the jump from pixi v4 to v7 retiring some of your function calls.

**Comment by TookieKun** [comment]
> > Appears broken under v11 stable, as well. Seems like the issue is the jump from pixi v4 to v7 retiring some of the calls you were using.
> 
> Quick fix to stop errors is changing mouse to pointer on line 486 of ruler.js. However, the ruler text doesn't work so there's more to it. Don't know enough about the module to debug it without it spitting out obvious errors.
> 
> Edit: Better to change that entire line to this below to remove the deprecation warning from PixiJS `const mousePosition = canvas.app.renderer.events.pointer.getLocalPosition(`
> 
> Edit 2: Got the ruler text working by just bypassing the if statement in _computeDistance to ensure it always enters the else part of it. This likely will break stuff but it worked for me.

Thanks to @MiniGrief 's instructions I made a version that seems to work fine without any issue besides it not having terrain compatibility for the meantime till an official/better release is released

https://github.com/TookieKun/foundryvtt-drag-ruler-partial-v11-compability/tree/develop

**Comment by manuelVo** [comment]
A v11 compatible version has just been released.
