### ISSUE TITLE
Support for the 3.5e rules.

### ISSUE THREAD

**Issue by Oryan77** [manuelVo/foundryvtt-drag-ruler#271]
Give support to D&D 3.5e movement and allow for creatures with a primary move speed other than "land" (like fly) to measure that speed instead of land speed.

**Comment by manuelVo** [comment]
Implementing the rules of specific game systems is the job of either the game system itself or third-party modules that bridge the gap between Drag Ruler and Game System (those modules are called game system integration modules). The [API section of the readme](https://github.com/manuelVo/foundryvtt-drag-ruler#api) details the technical details of doing such an implementation. If you're looking for real-life examples, you can have a look at the existing game system integrations (at least DnD5e and Pathfinder 1 implement support for flying speed, so those are probably good candidates to look at).
