### ISSUE TITLE
Moving 4 tiles diagonally has some graphic issues

### ISSUE THREAD

**Issue by Janonas** [manuelVo/foundryvtt-drag-ruler#272]
![drag ruler bug](https://github.com/manuelVo/foundryvtt-drag-ruler/assets/38334265/bf4ac090-4ca7-47bd-9a6d-f904fb8ccb9a)

**Comment by manuelVo** [comment]
What Foundry version are you using and which other modules are active?

**Comment by manuelVo** [comment]
I was able to confirm this with Terrain Ruler disabled in v11.
