### ISSUE TITLE
[Feature Request] Movement through enemies and terrain

### ISSUE THREAD

**Issue by GhostwheelX** [manuelVo/foundryvtt-drag-ruler#274]
Some monsters are able to move through terrain and creatures as though they were difficult terrain, even in the case of enemies or hard cover. (One example of such being the wraith's Incorporeal Movement ability from 5e.)

Might it be possible to implement a feature that allows this? Thank you 🙂

**Comment by manuelVo** [comment]
Just so I'm understanding correctly, which of those options are you requesting specifically?
- Add a feature to count moving through tokens as difficult terrain
- Add a feature that allows certain creatures to walk through walls (possibly counting the step through the wall as difficult terrain)

**Comment by GhostwheelX** [comment]
Both, separately, would be wonderful, so that you could either use them together or only one of them.

**Comment by manuelVo** [comment]
The first one is already possible. Install and activate the modules [Enhanced Terrain Layer](https://foundryvtt.com/packages/enhanced-terrain-layer) and [Terrain Ruler](https://foundryvtt.com/packages/terrain-ruler) and tweak their settings accordingly and Drag Ruler will apply difficult terrain cost when dragging through other tokens.

The second one is a bit tricky. If I were to add that feature to Drag Ruler, this has the potential to cause inconsistencies in the software, where a regular Drag allows a token to move through a wall while Ctrl+Drag doesn't, for example. So I think allowing certain tokens to move through walls should be implemented in a dedicated module.

**Comment by GhostwheelX** [comment]
Might there be a way to add a flag for the first one so that you could move through enemies without it appearing as though they're impassable terrain while the effect is active?

**Comment by manuelVo** [comment]
Foundry doesn't mark enemies as impassable terrain, so I'm not quite sure what you're talking about. Is this possibly a feature of another module you're using or maybe a feature of your game system?

**Comment by GhostwheelX** [comment]
Ah, it might be a property of Enhanced Terrain Layer, might be better to discuss it on their github if that's the case.
