### ISSUE TITLE
No printed measurement

### ISSUE THREAD

**Issue by n0q** [manuelVo/foundryvtt-drag-ruler#280]
Under v11, drag ruler no longer prints the distance measured. Tested on v11.301 across multiple systems, both with and without a grid.

![image](https://github.com/manuelVo/foundryvtt-drag-ruler/assets/7948363/31646d43-adab-46c4-a7e6-efa57293d2cc)

**Comment by YenBenGrey** [comment]
Just tested it myself and I thought the numericals were from a different module, I was doubting myself. 

However can confirm that there are no numericals. Even sneakily tried it in Crucidble. It shows the distance and the actor moves along but it doesn't match up with the new Action Point rules in combat.

**Comment by manuelVo** [comment]
> Obviously that's not an acceptable fix.

Surprisingly it is. The else-path contains everything that's necessary to handle both states: `this.dragRulerEnableTerrainRuler` being `true` and `false`. I have no clue how this redundant code path sneaked in there, but I suppose it probably happened during the migration to v10, where a major code refactor was necessary for compatibility.
