### ISSUE TITLE
Any chance of integrating this with the new Foundry RPG system Crucible? 

### ISSUE THREAD

**Issue by YenBenGrey** [manuelVo/foundryvtt-drag-ruler#282]
Definitely a request or enhancement :-)

**Comment by manuelVo** [comment]
Hi there. Drag Ruler does not contain any game system specific code. Game System integrations are provided either by the game system itself (unlikely for Crucible) or by third party modules (as is done for DnD5e for example). The game systems/modules can tell Drag Ruler how to behave via [Drag Ruler's API](https://github.com/manuelVo/foundryvtt-drag-ruler#api). In any case I'm willing to merge default values for Crucible into the generic speed provider. Feel free to open a PR if you're interested in getting those in (only small changes within the `systems.js` suffice to do so).

**Comment by YenBenGrey** [comment]
Unfortunately I have no idea how to do a Pull Request, is that for folk who want to make changes to your module? 

Crucible measures movement in squares not feet or metres. 

I clicked on a PR but it is all shaded out and I am not sure what I am doing ha ha :-/

**Comment by manuelVo** [comment]
PRs are a feature for people who want to contribute changes to a module. Usually (especially for larger changes) this requires fiddling about with a software named git, but for small changes (like adding those default values) you can do them in your browser using the github webpage like follows:

1. Open the file you want to edit in github (`systems.js` in your case).
2. Click the edit button (that's the button with the pencil icon)
3. Github will tell you that you need to fork the repository first. Click the green fork button to confirm (forking means the code will be copied into your github profile)
4. Perform the changes to the file as necessary
5. Press the green "Commit Changes..." button
6. In the window that opens, enter a description of your changes into the "Commit Message" field
7. Click "Propose changes". This should open a PR, which I can then use to get your changes into the module

That process may seem a bit overcompilcated. The reason it's done this way is that this creates a history that developers can go through to see what changed in the module and when and for what reason. This is invaluable when hunting down bugs and well worth the hassle :)
