### ISSUE TITLE
Not sure how to get a message to you other than this....it isn't really an issue but could be.....

### ISSUE THREAD

**Issue by YenBenGrey** [manuelVo/foundryvtt-drag-ruler#284]
Are you on Discord?

First thank you so much for helping me through a Pull Request, never done that before. 

Second thank you for doing it so quickly.

Third, in Crucible you can move 4 squares for free, then another 4 squares costs an action point. When you use the core Command(control)+Left click drag and you move the free movement, you use up your free movement, I think you get a chat card to confirm, then another up to 4 squares costs an AP and again you get a chat card to confirm. Then you lose an AP. 

Is this something that you think could be handled by Drag Ruler if dragging a token is mimicking Command(Control)+left click drag?

**Comment by manuelVo** [comment]
Yes, I am on discord. My discord handle is listed in the `module.json` of this module.

Regarding your question at hand: Yes, what you're suggesting can be done with Drag Ruler. However it's not possible using the Generic Speed Provider. A custom game system integration module is needed to accomplish what you're describing. Feel free to contact me on discord if you have any questions regarding this process.
