### ISSUE TITLE
Movement path line does not dissappear on other clients

### ISSUE THREAD

**Issue by Battenhatch** [manuelVo/foundryvtt-drag-ruler#285]
I'm seeing this behaviour both on the PC client on local network, and on Forge, with and without other modules loaded, with or without a dedicated movement provider module also loaded. It exsisted for me before todays update.

When more than one client is connected, the movent path traced by Drag Ruler dissappears for the client initiating the move when the token is released after the move - but on connected clients, the path stays visible. It can be made to go away by lifting the token again, dragging it outside it's new square/hex, then back to it and releasing it again.

The behaviour can be seen here (audio in danish so visuals only): https://youtu.be/OE40CkxMGXs

**Comment by manuelVo** [comment]
I'm having difficulties reproducing this in my local install. What game system are you using? Please also check the console (opens with F12) for any error messages or warnings.

**Comment by Battenhatch** [comment]
The only warning I see is this, but it pops the first time I move a token. It pops on the client doing the movement.

index.mjs:1 PixiJS Deprecation Warning: renderer.plugins.interaction has been deprecated, use renderer.eventsDeprecated since v7.0.0

It occurs with Simple Worldbuilding 0.8.1, which is the latest on Forge, and D&D 5e 2.2.1 on the PC client.

**Comment by manuelVo** [comment]
I managed to reproduce this. This bug apparently only happens on hex grids.

**Comment by manuelVo** [comment]
Actually, this happens on square grids as well, but not while a combat is running.

**Comment by Battenhatch** [comment]
Comfirmed, not on squares while combat is active.

**Comment by Avitale34** [comment]
Cool I was coming here to report this lol

**Comment by manuelVo** [comment]
This bug has been fixed upstream and should no longer occur when using Foundry v11.304
