### ISSUE TITLE
Add a hotkey to move a token without animation

### ISSUE THREAD

**Issue by DarKDinDoN** [manuelVo/foundryvtt-drag-ruler#3]
Hello,

Would be great if we have some kind of feature that allows GM to move a token without animation.
Sometimes we want to move players without them seeing the surrounding while moving.

Can be great for NPC's as well, so we can move them without the players seeing them move in their surrounding.

**Comment by dmrickey** [comment]
Can't you already do this with Core by just cutting/pasting the tokens?

**Comment by DarKDinDoN** [comment]
@dmrickey  Won't work if the token is in combat tracker for example
