### ISSUE TITLE
Add second waypoint type to denote action economy

### ISSUE THREAD

**Issue by JamzTheMan** [manuelVo/foundryvtt-drag-ruler#30]
Perhaps the API could support a second "waypoint" that also denotes "this was one 'action' worth of movement". This is so the color coding of the movement would be correct.

To expand upon the request in #22 It may be useful to know a token used an action or mode of movement that was shorter than it's normal "speed".

For example, in PF2e where you have 3 actions, you could move a 5' step, then a 20' stride, then another 5' step. You would have a max of speed x 3 (lets say 20' speed so 60' max) but in the above case, the 5' step is a whole action, so the token moved it's max of 30'.

The same would apply if mixing modes, like a climb, swim, burrow, etc. You may have walked 10 feet to a way (action 2) then climbed 15' up (action 2) then stride 20' (action 3). You have leaps/jumps as well.

The same would apply for using PF1E or DnD style "move + standard" action economy.

**Comment by manuelVo** [comment]
I feel like tracking action economy should really be it's own module that Drag Ruler then might be able to tap into to display the correct remaining speed.

In any case, more information about how other game systems handle this kind of thing would be appreciated and may change my mind about this.

**Comment by manuelVo** [comment]
The Pf2 integration module now has support for this. I'm pretty certain that this doesn't apply to DnD (you can split up a move action there) and Pf1 (you cannot move more than once per turn in that system). Since no other game systems have been mentioned that would profit from this I'm going to close the issue.
