### ISSUE TITLE
Persist path taken until next token move, end turn, keypress, or time

### ISSUE THREAD

**Issue by JamzTheMan** [manuelVo/foundryvtt-drag-ruler#31]
It would be useful if the path taken by a token would be shown even after the drag was done/completed. If the GM is busy and missed seeing the token moved, he may not have noticed the token moved over a trap, provoked an attack of opportunity, etc.

In another VTT we used an image of a footprint and placed it in each cell as a "tile". The previous path was always removed first when the next token on the map moved.

The persistence in Foundry could be until next token moves, you press a key, after x seconds, combat turn is over or ???

The UI could be colored/highlighted squares, or a line, etc, what ever is most performant?

**Comment by manuelVo** [comment]
Please check out 1.5.0 and see if the newly introduced movement history feature fulfills this request.

**Comment by JamzTheMan** [comment]
Looks good but I think we need a way to reset the movement.  

And not sure if resetting movement at the end of combat turn is best or reset at start of an actors turn?  Lets say, Ogre A goes first which prompts, say, a feat that lets Fighter B step up so Fighter B moves his token. Ogre A completes his turn, now it's Fighter B's turn to go (in the same combat round, he goes last).  The 5 foot step he took previously is counting against him.

Other game systems may vary on when an actors movement resets?

**Comment by JamzTheMan** [comment]
Oh, and a button or hotkey may be nice for to show (all?) paths to see if an Attack of Opportunity is viable? A player may want/need to see this but can't move an NPC token so can't?

**Comment by manuelVo** [comment]
If the implemented feature resolves the basic idea of the original request I'm going to close this. Resetting the path is tracked in #57. For your other feature ideas please open one issue per feature request. This helps me to easier keep track of what requests are still open.
