### ISSUE TITLE
Reset of movement during combact

### ISSUE THREAD

**Issue by seb9393** [manuelVo/foundryvtt-drag-ruler#314]
It would be great to have the possibility to reset the movement during combat.

**Comment by manuelVo** [comment]
There are two ways to do this:
- The player that moved the token presses Ctrl+Z. That moves the token back and also resets the movement history accordingly.
- The GM can reset the movement history through the menu that appears when he right-clicks the combatant in the combat tracker. This will leave the token at it's current position but clear the movement history.

**Comment by seb9393** [comment]
Great, sorry if I've not noticed this feature by my own. Thanks a lot

**Comment by manuelVo** [comment]
No worries. Enjoy the module.
