### ISSUE TITLE
Drag-ruler broken under v12 b319

### ISSUE THREAD

**Issue by n0q** [manuelVo/foundryvtt-drag-ruler#319]
It's that time again! Not too surprising, since v12 changes the grid api.

### Systems tested:
 - Dungeons and Dragons Fifth Edition
 - Hackmaster

### Modules installed:
 - Drag-Ruler
 - socketlib

### Steps to reproduce:
1.  Left click token on map.
2. Drag token.

### Expected result:
 - Should see a ruler line, with measurement.

### Observed result:
- No ruler line, no measurement.
- Token is frozen in place when let go. Old token is not erased.
- System crashes.

![image](https://github.com/manuelVo/foundryvtt-drag-ruler/assets/7948363/24a376a1-3292-4519-8772-2e418fb1e7d4)

**Comment by LabregoPT** [comment]
Just tried the module on the latest stable release (Build 12.324) and it is still broken. Having the same issue.

**Comment by n0q** [comment]
Duplicate of #324 . Closing.
