### ISSUE TITLE
Hex support broken, Freezing Tokens on foundry v12

### ISSUE THREAD

**Issue by Spaceferret42** [manuelVo/foundryvtt-drag-ruler#328]
I get this error here even after attempting to debug and fix the code that causes freezing on square grids
 Uncaught TypeError: canvas.grid.grid.options is undefined
[Detected 2 packages: drag-ruler, lib-wrapper]
    getAreaFromPositionAndShape util.js:160
    getAreaFromPositionAndShape util.js:155
    highlightTokenShape util.js:147
    highlightMeasurementNative foundry_imports.js:233
    performPostPathfindingActions ruler.js:188
    measure ruler.js:134
    scheduleMeasurement foundry_imports.js:153
    onMouseMove foundry_imports.js:145
    onEntityDragLeftDrop main.js:174
    forwardIfUnahndled main.js:81
    call_wrapper libWrapper-wrapper.js:616
    _onDragLeftDrop#0 libWrapper-wrapper.js:189
    callback foundry.js:30532
    #handleDragDrop foundry.js:30965
    #handlePointerUp foundry.js:30937
    notifyListeners EventBoundary.ts:1454
    notifyTarget EventBoundary.ts:658
    mapPointerUp EventBoundary.ts:992
    mapEvent EventBoundary.ts:231
    onPointerUp EventSystem.ts:428
[util.js:160:8](https://spaceferretmaingame.duckdns.org/modules/drag-ruler/src/util.js)

​

**Comment by Spaceferret42** [comment]
After applying the fix for freezing tokens square grids work fine. It is only when I attempt to move tokens on hex grids that I encounter the freezing tokens bug now

**Comment by VictorElHajj** [comment]
What fix?

**Comment by Spaceferret42** [comment]
The one posted in this thread for freezing tokens in v12  V12 Compatibility - freezes tokens #324

**Comment by manuelVo** [comment]
A new drag ruler version has just released which should have hex tokens work in v12
