### ISSUE TITLE
[Bug] Waypoint removal with the right click/spacebar when no waypoints have been established

### ISSUE THREAD

**Issue by Juanfrank** [manuelVo/foundryvtt-drag-ruler#33]
This is potentially a non-game breaking bug with the drag ruler, as the solution is generally easy and with no lasting effects. The behavior apparently arises when one hits the 'delete waypoint' key when no waypoints have been established, resulting in a 'ghost' token in your current location and the actual token remaining in the original space. Only the original space's token can be moved.

Steps to reproduce:
1. Have a token in the canvas and start dragging it using the Drag Ruler module.
2. Attempt to delete a waypoint using right-click or spacebar while dragging it.
3. Notice how a duplicate token graphic and a ghostly token remain in the canvas.
4. To clear the bug, move the token from the original position to any other place.

I believe this could be circumvented by 'gating' the 'remove waypoint' function behind a check for established waypoints. If no waypoints have been placed, either cancel the dragging, or make the downkey capture have no effect.

**Comment by manuelVo** [comment]
I cannot manage to reproduce the issue. Do you use a browser (if so, which?) or the electron Application? Do you have other Modules installed? If so, does the problem still occur if you disable all other modules except Drag Ruler?

**Comment by Juanfrank** [comment]
Upon checking the console, it seems that the bug itself comes from the TerrainLayer module and not this one, as it attempts to trigger an event function which does not exist.

```
10:32:22.381 Uncaught TypeError: event.stopPropagation is not a function
    _onDragLeftCancel http://127.0.0.1:35411/modules/TerrainLayer/terrain-main.js:44
    deleteWaypoint http://127.0.0.1:35411/modules/drag-ruler/src/main.js:237
    onRulerMoveToken http://127.0.0.1:35411/modules/drag-ruler/src/main.js:205
    moveToken http://127.0.0.1:35411/modules/drag-ruler/src/main.js:72
    _onSpace http://127.0.0.1:35411/scripts/foundry.js:2949
    _handleKeys http://127.0.0.1:35411/scripts/foundry.js:2805
    _handleKeys http://127.0.0.1:35411/modules/drag-ruler/src/main.js:110
    _handleKeys http://127.0.0.1:35411/modules/rangefinder/src/main.js:22
    _onKeyDown http://127.0.0.1:35411/scripts/foundry.js:2761
terrain-main.js:44:9
```

You may close this as that's something that needs to be addressed by another author.

**Comment by manuelVo** [comment]
Judging by the log you posted this is a incompatibility between Drag Ruler and Terrain Layer. So it's neither fully the fault of Drag Ruler nor Terrain Layer and the fix might actually require me to change code in Drag Ruler. I'm keeping this issue open until that incompatibility is resolved.

Are you using the original TerrainLayer module or the fork by ironmonk88?

**Comment by Juanfrank** [comment]
I'm actually using the fork provided by ironmonk88.

**Comment by manuelVo** [comment]
This module conflict has been solved by the other module in the meantime.
