### ISSUE TITLE
Hex grid sometimes has wrong start and end positions (Release v1.14.1)

### ISSUE THREAD

**Issue by aeauseth** [manuelVo/foundryvtt-drag-ruler#334]
Strange issues when using hex grids.  The start and end positions are sometimes wrong.  Sometimes doesn't highlight intervening hexes.

![image](https://github.com/user-attachments/assets/ec7fb104-d75f-4b49-86a2-816f1cf73069)

![image](https://github.com/user-attachments/assets/7e33c810-6c4b-4ba1-bc7e-b280a74fd7a8)

Using Drag Ruler 1.14.1
![image](https://github.com/user-attachments/assets/b4168dce-1014-4f20-8948-b51c748eae20)

![image](https://github.com/user-attachments/assets/073fb942-6694-4632-b310-225953331eaf)

**Comment by manuelVo** [comment]
The gaps in the path are now fixed. This might also fix the incorrect positions you were reporting. If this problem persists in the v1.14.2, feel free to reopen the issue.
