### ISSUE TITLE
Combatibility with The Dark Eye / Das schwarze Auge?

### ISSUE THREAD

**Issue by Danii0206** [manuelVo/foundryvtt-drag-ruler#35]
Hello,

I tried to use this module with the system DSA5. It does not recognize the speed attribute, so it measures every distance in green-color. The console logs this:

`The configured token speed attribute "data.status.speed.max" didn't return a speed value. To use colors based on drag distance set the setting to the correct value (or clear the box to disable this feature).`

The author of the system confirmed this is the correct attribute. Am I missing something or is this an incompatibility issue?

Kind regards
Danii

**Comment by manuelVo** [comment]
The attribute has to start at the token-level. Try `actor.data.data.status.speed.max` or ``actor.data.status.speed.max`

**Comment by Danii0206** [comment]
Thank you, works now. :)
