### ISSUE TITLE
Issue with Terrain Ruler + terrain layer

### ISSUE THREAD

**Issue by franckflo** [manuelVo/foundryvtt-drag-ruler#36]
It doesn't look like Drag Ruler is supporting Terrain Ruler and Terrain Layer yet, as seen in Screenshot. Do you have plan for supporting these two modules in the future?

**Comment by franckflo** [comment]
![DRAG RULER](https://user-images.githubusercontent.com/80221412/110744749-0bcbbb00-81ef-11eb-8dab-2a65d47b916a.jpg)

**Comment by manuelVo** [comment]
This feature will be part of the 1.4.0 release of drag ruler.

Duplicate issue: #1
