### ISSUE TITLE
Feature Request: Hold CTRL to Measure from Selected Token

### ISSUE THREAD

**Issue by Avitale34** [manuelVo/foundryvtt-drag-ruler#37]
A feature of show drag distance was to hold CTRL when selecting a token to get a ruler to appear coming from that selected token, would be amazing if you could add that to this module!

**Comment by manuelVo** [comment]
I don't think that this functionality fits well into Drag Ruler, as it's a fundamentally different function from what drag ruler does. For this reason I've put this runctionality into a separate module called [Rangefinder](https://foundryvtt.com/packages/rangefinder)

(Duplicate issue #6)
