### ISSUE TITLE
Toggle Drag Ruler on and Off

### ISSUE THREAD

**Issue by aceofknits** [manuelVo/foundryvtt-drag-ruler#41]
Low priority for an enhancement, but it would be helpful if we were able to toggle the drag ruler on and off.

For example, I would like to be able to turn this on in combat but have it off when there is free scene exploration

**Comment by manuelVo** [comment]
I'm thinking about an option that disables Drag Ruler by default and only activates it once the button that adds a waypoint is being clicked once. Would that feature sufficient to fulfill your request?

**Comment by GabrielDeschain** [comment]
I think it's a great suggestion! Another idea would be an option that only activates the Drag Ruler when we click on the start button and then deactivates the module again when the combat is over.

**Comment by manuelVo** [comment]
v1.8.0 contains the feature I suggested earlier. With this feature being present, is this request resolved from your point of view @aceofknits?

**Comment by CaosFR** [comment]
Hi, this option it's a very good idea but it's seen to dont work. 
When I select a token and use Ctrl + Left-Click Drag and Left-Click to add waypoint I have no color for walk, dash or unreachable. If automatically strat measuring is check the module work well.

Thanks

**Comment by manuelVo** [comment]
@CaosFR Ctrl+Drag is a foundry native function and doesn't have anything to do with Drag Ruler. When automatic measuring is disabled, press the button that adds a waypoint (spacebar or right click) while dragging to start measuring

**Comment by CaosFR** [comment]
@manuelVo Thanks for your help. With spacebar it's work very well.
May it's will be interessting to incoporate this mecanic to the native CTRL+Drag option.

**Comment by Merudo** [comment]
> I'm thinking about an option that disables Drag Ruler by default and only activates it once the button that adds a waypoint is being clicked once. Would that feature sufficient to fulfill your request?

I still think it would be nice to have an option to automatically turn the drag ruler off outside of combat, and fully turn it back on during combat.

There is rarely a need to measure movement distance outside of combat, and almost always a need for it during battle.

**Comment by CaosFR** [comment]
I'm agree, it's will be cool.

**Comment by manuelVo** [comment]
Closing, since from my point of view the original request is resolved.

The feature request to automatically enable Drag Ruler in combat and to automatically disable Drag Ruler out of combat is being tracked in #187
