### ISSUE TITLE
Tiny Token Snapping

### ISSUE THREAD

**Issue by velara** [manuelVo/foundryvtt-drag-ruler#48]
One of the recent updates has altered the behaviour of tiny tokens. Such that they now snap to intersections rather than to quarters of squares. With drag ruler active (and integration inactive). I can't give an exact update for which it broke but my game with drag ruler 1.3.1 has no issues, while the development setup with 1.4.3 has this issue.
![image](https://user-images.githubusercontent.com/74130268/112393473-bb5d5e80-8cc0-11eb-82f8-c86acb9b74d1.png)

While with drag ruler inactive tiny tokens snap like this 
![image](https://user-images.githubusercontent.com/74130268/112393365-8f41dd80-8cc0-11eb-8553-eaf440f733c4.png)

**Comment by manuelVo** [comment]
Is this an interaction with tiny tokens by blitz or with tiny tokens as vanilla foundry handles them.

**Comment by velara** [comment]
No modules are active except drag ruler in the development world. 
So it should be with tiny tokens as handled by vanilla foundry.
