### ISSUE TITLE
BUG: Tiny (1/4 square) token support

### ISSUE THREAD

**Issue by bsas** [manuelVo/foundryvtt-drag-ruler#49]
Systems that support tiny creatures to have small tokens so 4x can fit in a single square (examples dnd5e and pf2e) the tiny 1/4 square token of those creatures snap to the top left of the square naturally and you can drag them to another quarter of the square if needed, and when you move those tokens with the keyboard they always snap to the top left corner. But drag ruler makes those tokens snap to the center of the square

**Comment by manuelVo** [comment]
I wasn't aware that it's possible to choose the corner that the tiny token is occupying. I expected it to be locked to the top left. This is amazing!

Unfortunately foundries Ruler (which Drag Ruler uses internally if the Terrain Ruler module isn't present) doesn't behave too well when measuring distances that aren't going from center to center. I'll do some testing with corner snapping and if I don't encounter too many cases where that will cause weird behavior of the ruler I'll implement that feature into Drag Ruler.
