### ISSUE TITLE
Does not function at all when foundry.js has CRLF as line endings

### ISSUE THREAD

**Issue by Brimcon** [manuelVo/foundryvtt-drag-ruler#5]
Attempting to drag a token or even the ruler with no other modules selected spams the console with these errors:
![image](https://user-images.githubusercontent.com/7198283/106654897-8862de00-654d-11eb-9e42-4cb81f6eb7f3.png)
Using the Standalone Foundry program.

Edit: This gets printed immeditately upon starting up a world. Only happens with Drag Ruler enabled.
![image](https://user-images.githubusercontent.com/7198283/106655404-2787d580-654e-11eb-8754-1c863545eda6.png)

Foundry 0.7.9
D&D5e 1.2.4
Drag Ruler 1.0.1
Both as GM and as player.

**Comment by manuelVo** [comment]
This is probably an incompatibility with another module. Do you have any other modules than Drag Ruler activated? If so, please post the list of activated modules.

**Comment by Brimcon** [comment]
No other modules selected or active.
![image](https://user-images.githubusercontent.com/7198283/106661663-52762780-6556-11eb-9888-5e5db27d87fe.png)

**Comment by manuelVo** [comment]
I'm having difficulties reproducing this. What operating system are you using? Does this also happen when you use Chrome?

**Comment by Brimcon** [comment]
Windows 10. Same issue in Chrome and Firefox.

**Comment by manuelVo** [comment]
We continued this conversation in private and pinned the issue down to the `foundry.js` having `CRLF` line endings, which causes the patching mechanisms in Drag Ruler to break.
