### ISSUE TITLE
Drag Ruler doesn't support all features of the Enhanced Terrain Layer module

### ISSUE THREAD

**Issue by OLStefan** [manuelVo/foundryvtt-drag-ruler#50]
I am using this module together with [Enhanced Terrain Layer](https://foundryvtt.com/packages/enhanced-terrain-layer) instead of Terrain Layer.

And generally the difficult terrain is supported correctly. But Enhanced Terrain Layer has an option to treat tokens as difficult terrain which is correctly used by Terrain Ruler, but not by this module.

Terrain Ruler:
![image](https://user-images.githubusercontent.com/3206519/113478646-6c66b480-948a-11eb-98a7-6fb4c7891d44.png)

Drag Ruler:
![image](https://user-images.githubusercontent.com/3206519/113478665-856f6580-948a-11eb-9a8b-d76403402e82.png)

**Comment by manuelVo** [comment]
Drag Ruler currently doesn't support Enhanced Terrain Layer. Enhanced Terrain Layer has a compatibility mode that allows modules built for the old TerrainRuler module to work with Enhanced Terrain Ruler. However the compatibility mode doesn't support some features - like treating tokens as difficult terrain. Drag Ruler uses that compatibility mode and thus doesn't support those features.

Proper support for Enhanced Terrain Layer will come in Drag Ruler Version 1.5.0.
