### ISSUE TITLE
Bug: Tokens move errantly.

### ISSUE THREAD

**Issue by Burrowfield** [manuelVo/foundryvtt-drag-ruler#51]
https://imgur.com/G4aAAVy

Reproduction steps:

-  Create NPC
- Place NPC on canvas twice
- Move NPC 1 
- Move NPC 2 relatively quickly in a random direction.

Result: NPC 2 will move onto NPC 1 in a direct line.

Game system: Pathfinder

Happens without integration activated as well.

**Comment by manuelVo** [comment]
Unfortunately I was unable to reproduce this bug so far. What version of Drag Ruler do you have installed?

**Comment by CyricPL** [comment]
We had a very similar issue to this occur last night for players in our Dungeon Crawl Classics game (in DCC all players start with four zero-level PCs in their control). It was only occurring for users with Player level permissions - Trusted Player (with access to all system and module settings) and GM did not experience this issue. Running 1.4.5

**Comment by manuelVo** [comment]
Can you observe any errors/wanings in the javascript console (press F12 to open it) when this bug happens?
