### ISSUE TITLE
Feature Request: Pathfinding Ruler functionality for Drag Ruler

### ISSUE THREAD

**Issue by apoapostolov** [manuelVo/foundryvtt-drag-ruler#55]
This is the last big remaining functionality missing from Drag Ruler. 

The main reason why players need it is hard corners in dungeon maps where direct movement fails 3 of 4 attempts because players forget hard corners prohibit movement. This incredibly frustrates players and I have to remind them of hard corners all the time.

**Comment by caewok** [comment]
If Pathfinding Ruler and Drag Ruler implemented libRuler functionality, you should get pathfinding in Drag Ruler automatically if the Pathfinding module is enabled. I created a git pull in Pathfinding Ruler for the needed functionality:
https://github.com/mothringer/foundry-vtt-pathfinding-ruler/pull/7

Issue #101 covers the needed change for Drag Ruler.

**Comment by apoapostolov** [comment]
@manuelVo @caewok I know that Caewok implemented this in his forks via libruler, but is there a chance that the standard non-libruler version can get this functionality, perhaps integrated into drag-ruler rather than relying on a non-updated to V9 mod?

**Comment by itamarcu** [comment]
This feature has been available since version 1.11.0 so I think this issue can be closed.
