### ISSUE TITLE
Module prevents movement of a token with no linked actor

### ISSUE THREAD

**Issue by ben** [manuelVo/foundryvtt-drag-ruler#58]
When I have a token with no linked actor, this module prevents me from moving it around the map. In this example, I've got an actor-less token for my party's airship on the map.

![CleanShot 2021-04-18 at 10 11 54@2x](https://user-images.githubusercontent.com/39902/115154203-88dc2280-a02e-11eb-9b73-ce502ab268a1.jpg)

When I try to move the token around, the console fills with these errors, and I'm not able to move the token around.

<img width="622" alt="image" src="https://user-images.githubusercontent.com/39902/115154218-9ee9e300-a02e-11eb-8c25-312d35bd483f.png">

I know that first one doesn't really belong to this issue, but the other three look related.

**Comment by manuelVo** [comment]
I wasn't aware that there could actually be tokens without an actor. Thanks for reporting this!
