### ISSUE TITLE
Feature Request: Showing drag distance without draging the token

### ISSUE THREAD

**Issue by BarryBuckler** [manuelVo/foundryvtt-drag-ruler#59]
Hey mate, you made a wonderful module, thanks!!
I just switched from "show drag distance" module and it seems it had one feature your module lacks of.

While we are in token selection tool, we could simulate the distance a token could cover while holding the "Ctrl" key. Using this feature, allowed us to not actually drag the token until we were sure of the path/destination, and it prevents some movement by error by releasing the token instead of going back at the beginning of the measurement.

Is it possible to make it appear in your module? Or maybe it's a problem from my installation. I'm on 0.7.9.

**Comment by manuelVo** [comment]
Thanks for the nice feedback.

The feature you're requesting is called "Rangefinder". It's available via [a separate module that is called Rangefinder](https://foundryvtt.com/packages/rangefinder) as well.

Duplicate issue #6

**Comment by BarryBuckler** [comment]
> Thanks for the nice feedback.
> 
> The feature you're requesting is called "Rangefinder". It's available via [a separate module that is called Rangefinder](https://foundryvtt.com/packages/rangefinder) as well.
> 
> Duplicate issue #6

Yeah it doest that, but it does not include the color grading, your module has (for walk, dash, too far). Anyway to workaround that?

**Comment by manuelVo** [comment]
That currently is not possible. If you'd like Rangefinder to use DragRuler's colors, please open an issue about that in the Rangefinder repository, as that would be a feature that largely needs to be implemented there.
