### ISSUE TITLE
Compatibility Request: DCC

### ISSUE THREAD

**Issue by justinthejaguar** [manuelVo/foundryvtt-drag-ruler#60]
Would it be possible to make Drag Ruler compatible with the Dungeon Crawl Classics System?  I am unable to set the colors properly using the speed attribute of the system.

![image](https://user-images.githubusercontent.com/38022481/115414220-d9d14f80-a1c3-11eb-8fb0-11b2692d5397.png)

**Comment by manuelVo** [comment]
Generally Drag Ruler doesn't provide specific support for game systems. However the person from the screenshot is right. This incompatibility can be addressed by funneling the returned value through `parseInt`, so I'm going to treat this as a request to do that.
