### ISSUE TITLE
Tokens cannot be moved if their movement history goes through a wall

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [manuelVo/foundryvtt-drag-ruler#61]
**Submitted By**: Fox Reinhold#200
**Feedback Type**: Bug
 
**Core:** 0.7.9
**System:** dnd5e v1.2.4
**Module Version:** drag-ruler v1.5.3
**Dependency Version:** socketlib v1.0.3
 
**Description**:
With movement history enabled, using a multilevel tokens teleport that goes through a wall makes the token unable to be dragged anywhere as it believes it is still going through that wall.  Disabling history fixes it.<details>
<summary>Module Settings</summary>

```js
swapSpacebarRightClick: false,
alwaysShowSpeedForPCs: true,
showGMRulerToPlayers: true,
enableMovementHistory: true
```
</details>
<details>
<summary>Active Modules</summary>
1000-fish--v1.1.0;
CommunityLighting--v0.3.1;
SocketSettings--v0.0.3;
SoundBoard--v1.3.0;
TokensVisible--v1.4.0;
WhisperBox--v1.1.0;
_chatcommands--v1.3.2;
always-centred--v0.2.11;
autocomplete-whisper--v0.3.3;
baileywiki-maps--v0.2.7;
beyond20--v1.2;
bug-reporter--v1.2.1;
caeora-maps-tokens-assets--v1.0.4;
character-actions-list-5e--v3.0.3;
chat-images--v2.5.0;
chatdamagebuttons-beyond20--v1.1.2;
colorsettings--v2.5.9;
combat-numbers--v1.1.0;
compact-beyond-5e-sheet--v0.15.0;
compendium-browser--v0.4.5;
confetti--v1.0.2;
ddb-importer--v0.6.31;
df-chat-cards--v1.1;
df-chat-enhance--v3.0.2;
df-curvy-walls--v2.1.1;
df-settings-clarity--v3.1.0;
dice-calculator--v0.6.6;
dice-so-nice--v3.3.2;
drag-ruler--v1.5.3;
dragonfiremaps--v1.1.14;
enhanced-terrain-layer--v1.0.20;
fader--v0.0.2;
fudge--v1.1.1;
furnace--vv2.6.0;
fxmaster--v1.0.3;
gm-notes--v0.3;
grouproll--v0.7.1;
healthEstimate--v2.5.1.3;
hide-player-ui--v1.1.1;
illandril-chat-enhancements--v1.1.5;
illandril-token-hud-scale--v1.3.1;
laptop-fix--v0.0.8;
lib-df-hotkeys--v2.3.4;
lib-wrapper--v1.5.2.0;
mcromusic-sampler--v1.0.0;
milbys-maps-free--v1.1.7;
minimal-ui--v0.8.0;
mob-attack-tool--v0.1.22;
monks-little-details--v1.0.27;
monks-tokenbar--v1.0.33;
moonlight-maps-free--v1.1.0;
mre-dnd5e--v1.0.9;
multiattack-5e--v4.4.2;
multilevel-tokens--v1.3.4;
narrator-tools--v0.52;
parallaxia--v0.2.13;
perfect-vision--v1.8.4;
permission_viewer--v0.8.5;
plutonium--v1.26.1;
pointer--v2.3.1;
quick-status-select--v1.4.0;
raise-my-hand--v1.1.0;
reclusive-cartographer-maps--v1.0.0;
rounded-distance-for-measured-templates--v0.4.2;
smart-doors--v1.2.5;
smip-compendium--v0.5.0;
socketlib--v1.0.3;
streamMod--v0.2.7;
t-is-for-target--v0.3;
tabletop-rpg-music--v1.2.1;
terrain-ruler--v1.2.5;
token-hud-art-button--v1.1.3;
token-hud-wildcard--v1.2.0;
token-mold--v2.11.1;
tool-proficiencies-5e--v0.2.0;
torchlight--v0.9.0;
vtta-iconizer--v2.1.15;
vtta-tokenizer--v3.0.2;
wall-height--v3.5.3.4;
</details>

**Comment by foxreinhold** [comment]
I should have mentioned, this only occurs if the tokens are in combat/initiative and they make use of a MLT teleport with history enabled.

**Comment by manuelVo** [comment]
I think the collission check is being performed on the entire ruler instead of only on the new part. This is definitly a bug in Drag Ruler and will probably happen with any kind of teleport.

**Comment by Merudo** [comment]
I'm still experiencing this bug (or a variant) when using Drag Ruler 1.5.4 together with Multilevel Tokens 1.4.1.

In my tests, this bug occurs with only these two modules enabled.

Steps to reproduce:

- Create a teleport drawing
- Move a selected token through the teleport drawing
- After the teleport, try to move the selected token again - instead of moving, the token will become unselected.

Once unselected, it's possible to reselect the drawing, after which the token becomes movable again. This adds two clicks (one that auto-unselects the token, one to reselect it), making it both confusing and annoying to move a token through teleports.

This bug occurs for both players and DMs, and it happens whether a combat occurring or not.
