### ISSUE TITLE
Tokens cannot be moved right after an automatic teleport with Multilevel Tokens

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [manuelVo/foundryvtt-drag-ruler#62]
**Submitted By**: Merudo
**Feedback Type**: Bug
 
**Core:** 0.7.9
**System:** dnd5e v1.2.4
**Module Version:** drag-ruler v1.5.4
**Dependency Version:** socketlib v1.0.3
 
**Description**:
When using Drag Ruler 1.5.4 together with Multilevel Tokens 1.4.1, moving a token through an automatic teleporter drawing makes it temporarily unmovable.

Steps to reproduce:

- Create an automatic teleport drawing
- Move a selected token through the teleport drawing
- After the teleport, try to move the selected token again - instead of moving, the token will become unselected.

Once unselected, it's possible to reselect the token, after which the token becomes movable again. This adds two clicks (one that auto-unselects the token, one to reselect it), making it both confusing and annoying to move a token through teleports.<details>
<summary>Module Settings</summary>

```js
swapSpacebarRightClick: false,
alwaysShowSpeedForPCs: true,
showGMRulerToPlayers: true,
enableMovementHistory: true
```
</details>
<details>
<summary>Active Modules</summary>
bug-reporter--v1.2.1;
drag-ruler--v1.5.4;
multilevel-tokens--v1.4.1;
socketlib--v1.0.3;
</details>

**Comment by Merudo** [comment]
The bug occurs regardless of the following:

- Whether there is a combat or not
- Whether it is a player or the GM that is moving the token
- Whether there is a wall in the way
- Whether or not the "combat history" is enabled or disable

However, the bug doesn't occurs when

- Drag Ruler is disabled
- The teleportation is done through a map note

**Comment by manuelVo** [comment]
The way this happens is as follows:
- Drag Ruler first updates the tokens position, which makes the animation start on the other player's clients ([this happens here](https://github.com/manuelVo/foundryvtt-drag-ruler/blob/908600bfa392f399367dc0dae29bb48cc6037f91/src/foundry_imports.js#L70))
- After the update is sent to the other players Drag Ruler performs the animation locally and waits for the animation to finish (to do some cleanup afterwards, like removing the displayed ruler) ([this happens here](https://github.com/manuelVo/foundryvtt-drag-ruler/blob/908600bfa392f399367dc0dae29bb48cc6037f91/src/foundry_imports.js#L71))
- Multi Level Tokens gets notified that a token has been updated and that it's target position is on a teleporter. It then sends another update that puts the token onto the target position of the teleporter.
- The update that was triggered by Multi Level Tokens arrives while Drag Ruler's animation is running.
- A bug in FoundryVTT causes the animation to never finish or fail when the token is updated during the animation. This means that Drag Ruler will wait indefinitely, never being able to do it's cleanup (which in turn causes the bug described in this issue).

**Comment by manuelVo** [comment]
[Upstream bug report](https://gitlab.com/foundrynet/foundryvtt/-/issues/4902)

**Comment by manuelVo** [comment]
The upstream bug has been resolved and I've verified this bug to be gone in 0.8.7.
