### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAltOrientationFlag' of undefined

### ISSUE THREAD

**Issue by crnormand** [manuelVo/foundryvtt-drag-ruler#63]
I am trying to implement support for our GURPS Game Aid, however, using a HEX Column map, I am getting:

```
util.js:120 Uncaught TypeError: Cannot read property 'getAltOrientationFlag' of undefined
    at applyTokenSizeOffset (util.js:120)
    at Ruler.measure (foundry_imports.js:113)
    at Ruler.measure (main.js:100)
    at Ruler.onMouseMove (foundry_imports.js:97)
    at Token.onTokenLeftDragMove (main.js:172)
    at Token._onDragLeftMove (main.js:51)
    at MouseInteractionManager.callback (foundry.js:36392)
    at MouseInteractionManager._handleDragMove (foundry.js:36724)
    at MouseInteractionManager._handleMouseMove (foundry.js:36698)
    at e.a.emit (index.js:202)

```
Whenever I try to move a token.

CONFIG.hexSizeSupport is undefined.

It works fine if the map is in Square mode.

My code is:
```

  //Add support for the Drag Ruler module: https://foundryvtt.com/packages/drag-ruler
  Hooks.once("dragRuler.ready", (SpeedProvider) => {
    class GURPSSpeedProvider extends SpeedProvider {
        get colors() {
            return [
                {id: "walk", default: 0x00FF00, name: "GURPS.dragrulerWalk"},
                {id: "sprint", default: 0xFFFF00, name: "GURPS.dragrulerSprint"},
                {id: "fly", default: 0xFF8000, name: "GURPS.dragrulerFly"}
            ]
        }

        getRanges(token) {
          const baseMove = token.actor.data.data.currentmove

          // A character can always walk it's base speed and sprint at 1.2X
          const ranges = [
            {range: baseMove, color: "walk"},
            {range: Math.floor(baseMove * 1.2), color: "sprint"}
          ]
    
          // Character is showing flight move
          if (!!token.actor.data.data.additionalresources.showflightmove)
            ranges.push({range: token.actor.data.data.currentflight, color: "fly"})
          return ranges
        }
    }
    dragRuler.registerSystem("gurps", GURPSSpeedProvider)
})
```

**Comment by crnormand** [comment]
And it works great on Square maps.   However, GURPS is mainly a hex based system... so ;-)

**Comment by manuelVo** [comment]
Your code looks fine, so I think this is probably a bug within Drag Ruler. However I cannot verify this until monday.

Does this also happen if you use the Generic Speed Provider?

In the meantime you can activate the Hex Size Support module as a workaround. It should make that bug go away (generally I'd recommend that module if you're using hex grids).

**Comment by crnormand** [comment]
It doesn't work with the Generic Speed Provider.  It shows the same error.

It does, however, work when the Hex Token Size Support module is loaded.   ;-)

**Comment by manuelVo** [comment]
Hex grids are definitely better supported in drag ruler if HexSizeSupport is enabled. However it should still work without that module. I'll have a look on monday

**Comment by manuelVo** [comment]
I cannot reproduce this bug. What version of Drag Ruler do you have installed? Do you have other modules besides Drag Ruler installed? If so, does the bug still occur if you disable all Modules except Drag Ruler (and it's dependency libsocket)?

**Comment by manuelVo** [comment]
Judging from the error message you've posted you're likely on an old version of Drag Ruler. This issue has likely been already fixed. Please update Drag Ruler. If the issue persists with the current Drag Ruler version, feel free to reopen this issue.

**Comment by crnormand** [comment]
I am running on v1.6.0.   I searched through the code for 'getAltOrientationFlag', and it doesn't exist in the foundry.js.    I then searched through all of the modules that I have downloaded, and it only appears in two, drag-ruler and hex-size-support.   And it is only defined in hex-size-support.   So if you do not have hex-size-support loaded, you WILL get that error.

The red arrow shows the only place that that function is defined (in hex-size-support) and the green arrow shows were it is being used in drag-rule (without ever being defined).
![image](https://user-images.githubusercontent.com/8931036/116551929-71225b00-a8c6-11eb-9e9a-6e9f05289b91.png)

**Comment by manuelVo** [comment]
Yes, `getAltOrientationFlag` is a function that is provided by Hex Token Size Support. However it shouldn't ever be called when that module isn't present. Please paste the error (with stack trace) here as it's produced by v1.6.0. That'll help me figure out where things are amiss.

**Comment by crnormand** [comment]
util.js:120 Uncaught TypeError: Cannot read property 'getAltOrientationFlag' of undefined
    at applyTokenSizeOffset (util.js:120)
    at Ruler.measure (foundry_imports.js:113)
    at Ruler.measure (main.js:100)
    at Ruler.onMouseMove (foundry_imports.js:97)
    at Token.onTokenLeftDragMove (main.js:172)
    at Token._onDragLeftMove (main.js:51)
    at MouseInteractionManager.callback (foundry.js:36392)
    at MouseInteractionManager._handleDragMove (foundry.js:36724)
    at MouseInteractionManager._handleMouseMove (foundry.js:36698)
    at e.a.emit (index.js:202)

There doesn't seem to be a check to see if hex-size-support is loaded before it attempts to call getAltOrientationFlag() on line 120

const isAltOrientation = CONFIG.hexSizeSupport.getAltOrientationFlag(token);

And again, this only occurs on HEX maps.

**Comment by manuelVo** [comment]
Hmm that error message still looks like it is coming from an old version. Especially since there is no call to applyTokenSizeOffset in [line 120 of `util.js`](https://github.com/manuelVo/foundryvtt-drag-ruler/blob/b5ea1f2284118fd082a37b406c4e4853b530bee5/src/util.js#L120).

Try reloading foundry with Ctrl+Shift+R to see if that makes the error go away (or at least changes the error message).

**Comment by crnormand** [comment]
Although the module said 1.6.0, to be certain, I just deleted it completely and re-installed it.   I can see the different code now.  So I did have an older version (and I have no idea why Foundry said 1.6.0 was installed).

Thank you for your time.
