### ISSUE TITLE
Diagonal Movement calculated wrong

### ISSUE THREAD

**Issue by Smart-Helper** [manuelVo/foundryvtt-drag-ruler#65]
Hello,

even though i enabled the diagonal movement rule to be euclidean
![grafik](https://user-images.githubusercontent.com/38812603/116811961-75f84080-ab4c-11eb-85b0-488d3bf75d30.png)

it doesnt calculate it correct and just takes 5ft. for every diagonal move. 
![grafik](https://user-images.githubusercontent.com/38812603/116811998-9e803a80-ab4c-11eb-91f1-7f2c6fc0700c.png)

I tried to install the PF2 Integration in hopes i get the correct measurement now but after installing the module i dont see any difference and dont even see the module in my module management nor in the Drag Ruler configurations.
![grafik](https://user-images.githubusercontent.com/38812603/116812071-0040a480-ab4d-11eb-92aa-f334cec2d057.png)
![grafik](https://user-images.githubusercontent.com/38812603/116812094-2bc38f00-ab4d-11eb-88d0-e3480a5faf7f.png)

Is there a way to fix this? We use diagonal movement quite frequently and it has to be correct for us otherwise we cant use this module.

Thanks in advance

**Comment by manuelVo** [comment]
The Pf2 module only works in Pathfinder 2e, as the name suggests. This is the reason wh it's not listed in the module management.

Do you have the Terrain Ruler module installed? If so, try if deactivating that module solves the issue and please report the results.

**Comment by Smart-Helper** [comment]
Yeah, disabling the terrain ruler did the trick. Now it measures perfectly fine.

But when i apply difficult terrain via Enhanced Terrain Layer it doesnt apply the difficult terrain to your drag ruler so we have to count it manually again and...Is there a way to work around this?

**Comment by manuelVo** [comment]
Terrain Ruler currently doesn't support euclidian measurements. Since this isn't a bug in Drag Ruler itself I'm going to closr this issue. However if you would like to see support for that in Terrain Ruler, feel free to open an issue in the Terrain Ruler repo.

Until Terrain Ruler supports euclidian distances a possible workaroud would be using the 5/10/5 grid rule, which is a pretty good approximation of euclidian.
