### ISSUE TITLE
[BUG} Malfunction in the Tormenta 20 system

### ISSUE THREAD

**Issue by GabrielDeschain** [manuelVo/foundryvtt-drag-ruler#69]
In newer sheets of the Tormenta 20 system, the color of the ruler is not changing according to the speed of the token. The ruler is always the same color as the standard player regardless of the speed of his token. In older monster sheets, I realized that the module works normally. And the problem persists even when Drag Ruller is the only active module. I suppose it is something about how the system measures distance in new tokens. Drag Ruller just seems to recognize how to measure distance from tokens linked to older sheets
![Sem to](https://user-images.githubusercontent.com/83513356/117723932-6d8dae80-b1b9-11eb-8f6b-1e4c331eea83.png)
.

**Comment by GabrielDeschain** [comment]
![imagem_2021-05-10_180323](https://user-images.githubusercontent.com/83513356/117724359-03c1d480-b1ba-11eb-9c3b-794992a05f1b.png)

**Comment by manuelVo** [comment]
Which version of Drag Ruler do you have installed? Judging from the screenshots I suspect it's quite old. The current version is 1.6.4. If you are on an older version of Drag Ruler updating might resolve the issue.

**Comment by GabrielDeschain** [comment]
I think it is the most current
![imagem_2021-05-12_160314](https://user-images.githubusercontent.com/83513356/118030354-8f16a380-b33b-11eb-916d-16085b84fabb.png)

**Comment by manuelVo** [comment]
In this case, please check the following three things:
- Open Drag Ruler's Speed Provider Settings and check which speed provider is selected
- Open the console (pressing F12 opens the console) and check if there are any errors (red) or warnings (yellow) in there
- Also in the console, click on the empty space at the bottom, type `Ruler` and press enter. Check if first line that's printed starts with `class Ruler extends PIXI.Container` or `class DragRulerRuler extends Ruler` (or something entirely different).

**Comment by GabrielDeschain** [comment]
1º
![image](https://user-images.githubusercontent.com/83513356/118060812-0531ff00-b36a-11eb-91fc-68020996f314.png)I 

2º I found some errors in the Console: 
![image](https://user-images.githubusercontent.com/83513356/118061105-ad47c800-b36a-11eb-9aa0-b237e1f0e65a.png)

3º Yes.
![image](https://user-images.githubusercontent.com/83513356/118061177-cd778700-b36a-11eb-8be0-61974359ee88.png)

**Comment by manuelVo** [comment]
Judging from those screenshots, the bug is in the speed provider that's bundled with the tormenta20 game system, not in Drag Ruler itself. This means you'll need to report this bug to the developers of the Tormenta20 system.

https://gitlab.com/vizael/Tormenta20

**Comment by GabrielDeschain** [comment]
Ok! Thanks!
