### ISSUE TITLE
Ability to configure color palette

### ISSUE THREAD

**Issue by Brimcon** [manuelVo/foundryvtt-drag-ruler#7]
Something Show Drag Distance had was the ability to change colors based on dash or too far within Foundry itself. Great for those who have Colorblindness.

**Comment by manuelVo** [comment]
I'm not very familiar with colorblindness. Is it hard for colorblind people to discern yellow from red? If so, is there a set of colors that's known to be easy to discern for all people, no matter which kind of color blindness have? If so, I think a checkbox to enable color blindness mode would be more user friendly than prompting the user to enter colors.

**Comment by Brimcon** [comment]
It really depends on the colorblindness. Some people have red/yellow Blindness where the red looks just like a darker shade of yellow. Some have Green/Red blindness, so if they have green as their primary player color, it would look similar to the red of "Too far away" Again, options are good IMO.
