### ISSUE TITLE
libwrapper reports conflict with TouchVTT

### ISSUE THREAD

**Issue by GreatGraySkwid** [manuelVo/foundryvtt-drag-ruler#75]
Hey, libwrapper is reporting the following issues, and I'm not savvy enough to grok whether you or the TouchVTT dev would be able to resolve it, so I'm posting on both modules:
"Potential conflict detected between module 'drag-ruler' and module 'touch-vtt'.
Detected non-libWrapper wrapping of 'MeasuredTemplate.prototype._onDragLeftStart' by module 'drag-ruler'. This will potentially lead to conflicts."
"Potential conflict detected between module 'drag-ruler' and module 'touch-vtt'.
Detected non-libWrapper wrapping of 'MeasuredTemplate.prototype._onDragLeftMove' by module 'drag-ruler'. This will potentially lead to conflicts."
"Potential conflict detected between module 'drag-ruler' and module 'touch-vtt'.
Detected non-libWrapper wrapping of 'MeasuredTemplate.prototype._onDragLeftDrop' by module 'drag-ruler'. This will potentially lead to conflicts."
"Potential conflict detected between module 'drag-ruler' and module 'touch-vtt'.
Detected non-libWrapper wrapping of 'MeasuredTemplate.prototype._onDragLeftCancel' by module 'drag-ruler'. This will potentially lead to conflicts."

**Comment by manuelVo** [comment]
All this error message means is that libwrapper cannot gurantee that there are no conflicts between Drag Ruler and libwrapper. When this message shows up this doesn't necessarily mean that there is an issue, just that there *could* potientally be issues.

Did you notice any conflicts between the modules (i.e. one module breaking while the other is active)?

**Comment by GreatGraySkwid** [comment]
No, but I only have one user using TouchVTT and they weren't playing last session. I will let you know if issues occur in the future.

**Comment by manuelVo** [comment]
I gave TouchVTT a shot yesterday and it seems to be working fine with Drag Ruler.
