### ISSUE TITLE
Conflict with Multilevel Tokens

### ISSUE THREAD

**Issue by kgruszcz** [manuelVo/foundryvtt-drag-ruler#79]
Enabling Drag Ruler cause Multilevel Tokens to teleport the back to the starting location when approaching a teleporter from any direction other than directly left or right.

**Comment by manuelVo** [comment]
This also happens in Multi Level Tokens when you use Foundries core functionality measure+spacebar to move the token. For this reason I think that this is a bug within MLT, not in Drag Ruler. Please open an issue about this in the MLT repository.

**Comment by kgruszcz** [comment]
While I do agree that MLT has it's own issue the last bit of movement happens after the token teleports.  The main issue I have with this bug is that the teleporter stops working, not the animation issue.

What happens is after the teleportation, I'm reset to the starting position.  What I think is happening is that something in drag ruler is saving the start position and pushing that back out after the token teleports.  I know in the 0.8.X the changed the way position updates come through the API. If you only move in the X or Y direction, the API only sends out information about the respective direction.  The reason I get partial teleports, I surmise, is that drag ruler only returns the relevant movement. So I only get reset in the partial directions.
