### ISSUE TITLE
Gridless Path Coloring

### ISSUE THREAD

**Issue by n0q** [manuelVo/foundryvtt-drag-ruler#8]
Rulers are most useful for gridless play, and I'd love for players to get the same visual feedback in gridless as they do with a grid. I realize you probably can't color the squares (because there aren't any) but perhaps you could work in visual indicators in some other fashion?

**Comment by manuelVo** [comment]
Just realized that #15 and this issue are duplicates. I'm closing this issue in favor of #15, because #15 deilvers a good idea on how to accomplish this (which I plan to implement).
