### ISSUE TITLE
Depreciation warning spam on VTT 0.8.6

### ISSUE THREAD

**Issue by minakitty** [manuelVo/foundryvtt-drag-ruler#80]
Console is, when loading world, giving me 800+ warnings of "The Document#_id property is deprecated in favor of Document#id or Document#data#_id. Support will be removed in 0.9.0"

It was causing so much lag other players not in the LAN couldn't properly. Find the Culprit module identified this mod as the source of all the errors.

This has affected multiple worlds, using both the PF1 and DND5e systems

**Comment by manuelVo** [comment]
Which Version of Drag Ruler are you using?

**Comment by minakitty** [comment]
1.7.3 with socketlib 1.0.6

**Comment by manuelVo** [comment]
That's odd... I cannot reproduce this in my test setup. Check if uninstalling and freshly installing drag ruler helps (in rare cases foundry isn't updating modules correctly. I suspect this may be the case here)

**Comment by Battenhatch** [comment]
Here at my end I see this error also. It does not seem to be related to Drag Ruler, however. In a clean world the error starts occurring when I enable the Cursor Hider module, not Drag Ruler.

**Comment by manuelVo** [comment]
Since the initial author didn't respond anymore and no one else seems to have this problem I'm going assume that this was a fluke in the update process and is resolved.
