### ISSUE TITLE
Incompatibility with Multilevel Tokens on 0.8.6

### ISSUE THREAD

**Issue by vanderleitelesjr** [manuelVo/foundryvtt-drag-ruler#82]
If the module Multilevel Tokens is enabled, there is a visual glitch whenever the token lands on a drawing set to run a macro. For example, I usually use Multilevel Tokens to set up elevation drawings across my maps, to automatically update a token's elevation whenever they move into specific areas, if Drag Ruler is enabled the tokens are sent flying past their intended destination whenever they are dragged into a drawing with the macro that changes their elevation:

![Glitch](https://user-images.githubusercontent.com/40318093/120942728-2e437680-c701-11eb-813e-2df5a0497589.gif)

**Comment by manuelVo** [comment]
A similar bug was recently fixed in MLT. Check if updating solves the issue. If not, please check if this bug also occurs when moving the token with Ctrl-Measure+Spacebar.

**Comment by manuelVo** [comment]
Closing, because there was no response from the Issues author, so I'm assuming it's indeed fixed. Feel free to repoen this issue if the conflict persists.
