### ISSUE TITLE
[BUG] Metric system compatibility

### ISSUE THREAD

**Issue by DarKDinDoN** [manuelVo/foundryvtt-drag-ruler#85]
Hello,

There is an issue with the metric system using decimal for movements, like 7.5 or 10.5.
I think it comes from using parseInt instead of parseFloat functions.

**Comment by manuelVo** [comment]
I'm having difficulty following what the problem exactly is. Which settings are you using for your scene and what's the tokens speed? What effects do you observe and how do they differ from what you'd expect?

**Comment by DarKDinDoN** [comment]
@manuelVo Sorry for the crappy explanation.
![image](https://user-images.githubusercontent.com/1687854/122998680-a2db0e00-d3ad-11eb-8fd3-da0ba97ff280.png)

As you can see on the screenshot, the character has a walk movement of 7.5.
But the latest (bottom) highlighted square is yellow. It should be greeN

And I think that it comes from the fact that this module is using parseInt insteand of parseFloat to parse the character movement.
parseInt(7.5) would translate as 7.

**Comment by manuelVo** [comment]
Hmm I cannot reproduce this in DnD5e. What game system are you using? And which Speed Provider?

**Comment by manuelVo** [comment]
Nevermind, my test setup was flawed. I can reproduce this now and your diagnosis of the bug is likely correct.
