### ISSUE TITLE
Apparent conflict with Token Attacher

### ISSUE THREAD

**Issue by iotech-fvtt** [manuelVo/foundryvtt-drag-ruler#87]
I'm having an issue with Drag Ruler and Token Attacher on 0.8.8 self hosted. Player or GM, example: Move any token from A to B distance X in direction Y= on drag release, token draws at B, then moves in direction Y for X distance, passing through walls and providing vision, then snaps back to B.

Confirmed normal operation with either Drag Ruler or Token Attacher disable, but with both enabled, the above behavior is observed.

**Comment by manuelVo** [comment]
I just gave this a test and this also happens in Token Attacher when Drag Ruler is disabled by moving the Token using Measure+Spacebar. A such this is a bug in Token Attacher and is unrelated to Drag Ruler.
