### ISSUE TITLE
suggestion: tokens as a double movement

### ISSUE THREAD

**Issue by Fridan99** [manuelVo/foundryvtt-drag-ruler#89]
It would be useful to contemplate double movement when the line of trajectory passes through an allied or enemy creature (token), as it happens in the d&d 5e rules.  
Example: a creature moving through a square occupied by another creature (token), instead of using 5 feet, would use 10 feet.

**Comment by manuelVo** [comment]
This (and all other modes of diffiult terrain) are already supported. To get it working you need to install "Enhanced Terrain Layer" and "Terrain Ruler" alongside Drag Ruler and enable the appropriate setting in "Enhanced Terrain Layer" .
