### ISSUE TITLE
While Drag Ruler is enabled, no precise positioning possible

### ISSUE THREAD

**Issue by tagnullde** [manuelVo/foundryvtt-drag-ruler#9]
While the module is active I am not able to hold SHIFT and place the token "outside" of the grid.
Maybe it's possible to disable the ruler temporarily while SHIFT is pressed so I can position a token properly.

Foundry: 0.7.9
DND: 1.2.4
Ruler: 1.0.1

**Comment by giogreymon** [comment]
yes, just wanted to add I am experiencing this as well

**Comment by davesturtevant** [comment]
Also came here looking to mention this.

**Comment by OfficerHalf** [comment]
You can still place a token on the canvas while holding shift, but then it will forevermore be stuck with an offset from the grid. 😄

**Comment by manuelVo** [comment]
During initial work on this issue I've noticed that behavior as well. Luckily both issues are so closely tied together that once the fix for this issue lands the bug with tokens getting stuck offset from the grid will be gone as well.
