### ISSUE TITLE
Feature: Add CoC compatibility

### ISSUE THREAD

**Issue by lozalojo** [manuelVo/foundryvtt-drag-ruler#91]
For HavlockV/CoC system:

https://github.com/HavlockV/CoC7-FoundryVTT

Thanks, and great work!

**Comment by manuelVo** [comment]
Hi there. There are two ways to make Drag Ruler compatible with the game system of your choice. You can modify Drag Ruler's Speed Provider Setting, adjusting the parameters of the Generic Speed Provider to fit the rules of your game system.
If you're interested in having Drag Ruler ship those settings by default, please open a PR that modifies the [systems.js file](https://github.com/manuelVo/foundryvtt-drag-ruler/blob/develop/src/systems.js) accordingly.

A deeper integration of game systems is outside of the scope of the core Drag Ruler module. To achieve a deeper integration of your game systems rules (for example when two speed ranges aren't enough, when the running speed cannot be represented by a muliplier of the base speed or when a flying token needs to switch to a fly speed) Drag Ruler can be told about these details via it's [API](https://github.com/manuelVo/foundryvtt-drag-ruler#api). Simply write a small module (or directly integrate it in to the according game system) and a pretty deep integration into your game system becomes possible.

**Comment by lozalojo** [comment]
Ops, let me take a deeper look, but apparently is quite easy. I'll ask here if I face any problem

Thank you

**Comment by manuelVo** [comment]
If you're not feeling comfortable with editing code you can tell me the correct settings and I'll add them to the code. However finding the correct settings is up to you since I don't know the first thing about the game system you linked.

**Comment by lozalojo** [comment]
Fixed here:

https://github.com/manuelVo/foundryvtt-drag-ruler/pull/92

Close the issue when you accept the PR, thank you!
