### ISSUE TITLE
Compatibility issue with Your Tokens Visible

### ISSUE THREAD

**Issue by thatlonelybugbear** [manuelVo/foundryvtt-drag-ruler#98]
Repost from https://github.com/David-Zvekic/TokensVisible/issues/21

Using Drag Ruler (v1.7.7) on Foundry 0.8.8, and Your Tokens Visible (v2.5.2) with the option for walls to cancel animation checked.

As a GM when you drag a token over a wall the animation is cancelled, but the ruler that appears when you drag the token is visible for the duration that the actual move would have taken.

If you right click while the token is moving, the drag ruler disappears and from that moment onwards, for the selected token the drag ruler vanishes as intended (now and then when you pick up the token and move it a bit fast the movement is not registered at all though as a side issue).

If you choose another token at any point or deselect the first token, the same issue appears again and so on.

In the video the aforementioned behaviour is shown and just before I start moving the tokens around rapidly, I have right clicked to make the drag ruler template disappear faster.

https://user-images.githubusercontent.com/7237090/125338981-c78d2a80-e348-11eb-949a-65232a0033cf.mp4

Quoting Tokens Visible module owner:

> I would report this issue to Drag Ruler.
> 
> Drag Ruler draws and erases the ruler, not YTV.
> Drag Ruler should probably wrap Token.prototype.setPosition if it wants to
> guarantee that the duration of the ruler rendering always matches the
> duration of the animation rather than assuming a duration.
> After setPosition returns then the animation is complete.

**Comment by manuelVo** [comment]
This bug does also occur in "Your Tokens Visible" when Drag Ruler is disabled when moving the token via Measure+Spacebar, meaning Drag Ruler doesn't have anything to do with this bug occuring.
